apache/arrow-nanoarrow

.clang-format
.github/workflows/build-and-test.yaml
.gitignore
CMakeLists.txt
CMakePresets.json
CMakeUserPresets.json.example
README.md
src/nanoarrow/allocator.c
src/nanoarrow/allocator_test.cc
src/nanoarrow/buffer.c
src/nanoarrow/buffer_test.cc
src/nanoarrow/error.c
src/nanoarrow/error_test.cc
src/nanoarrow/metadata.c
src/nanoarrow/metadata_test.cc
src/nanoarrow/nanoarrow.c
src/nanoarrow/nanoarrow.h
src/nanoarrow/schema.c
src/nanoarrow/schema_test.cc
src/nanoarrow/schema_view.c
src/nanoarrow/schema_view_test.cc

This PR imports the preliminary work from https://github.com/paleolimbot/nanoarrow (with reviews from @lidavidm and @pitrou and input from the dev mailing list via the [initial design document](https://docs.google.com/document/d/11n7ICVZO8exZ-z3GRlI26VLzKPXlYlEz5xjLl1y0ujU/edit?usp=sharing) ).

Add files from paleolimbot/nanoarrow

---

.github/workflows/build-and-test.yaml
CMakeLists.txt
valgrind.supp

Attempt memcheck + suppressions

---

.github/workflows/build-and-test.yaml
CMakeLists.txt
src/nanoarrow/array.c
src/nanoarrow/array_test.cc
src/nanoarrow/array_view.c
src/nanoarrow/array_view_test.cc
src/nanoarrow/bitmap_inline.h
src/nanoarrow/schema_test.cc

Fix memcheck in CI (and memcheck errors in C)

---

.asf.yaml

Tune down notifications

---

src/nanoarrow/buffer_inline.h
src/nanoarrow/buffer_test.cc

[C] Fix bit counting for a single byte

---

.github/workflows/docs.yaml
README.md
docs/.gitignore
docs/README.md
docs/source/c.rst
docs/source/conf.py
docs/source/index.rst
src/nanoarrow/nanoarrow.h
src/nanoarrow/nanoarrow_types.h

This PR makes a few adjustments to the documentation in the headers and the sphinx setup to get a website that mirrors the content in the README, inline documentation, and the R auto-geneated pkgdown site.

[Documentation] Improve documentation

---

README.md

Fixes a broken image link on the main page

[MINOR][Documentation] Fix badge on readme

---

src/nanoarrow/schema_test.cc

fix: Ensure tests pass on big endian

---

CMakeLists.txt
dev/release/verify-release-candidate.sh

fix: Support centos7/gcc 4.8 for CMake build + test workflow

---

dev/release/README.md

chore: Update Arch linux package list for release verification

---

r/DESCRIPTION

chore(r): Fix DESCRIPTION as per CRAN requests

---

src/nanoarrow/nanoarrow.hpp

chore: Fix C++ warnings causing ADBC R package errors

---

docs/source/getting-started.md

Thanks for adding the nice example.  While perusing it (and I need to read it fully) I spotted a simple missing comma in the enumeration of possible install commands.  That's makes it possibly to most insignificant PR ever but hey we believe in incremental fixes.  Feel free to close it if you'd rather address it elsewhere / as part of a larger commit.

Add missing comma

---

.github/workflows/bundle.yaml

...apparently this wasn't actually committing all of the files!

chore: Fix nightly bundling workflow

---

CMakeLists.txt
src/nanoarrow/array.c

chore: Initialize variable causing problems with `-Wmaybe-uninitialized`

---

.github/workflows/docker-build.yaml

chore: Login to container repository in Docker build workflow

---

r/NEWS.md
r/README.md
r/cran-comments.md

A few repo-tidying items resulting from a dry run of #222.

chore(r): Tidy R package for CRAN submission

---

.github/workflows/r-check.yaml
src/nanoarrow/buffer_inline.h
src/nanoarrow/buffer_test.cc

fix: Fix bad access crash in `ArrowBitmapByteCountSet()`

---

dev/release/README.md
dev/release/post-01-upload.sh

Filling in a few items while I remember the details!

chore(dev/release): Improve release and post-release instructions

---

docs/source/getting-started.md

Hey @paleolimbot, I went through every bit of the Getting Started guide and found a few things. Overall I found the guide to be very well-written and super helpful so all I have here are small changes. See each commit message body for details on each fix and feel free to take or leave any.

Various fixes/edits in getting-started.md

---

.pre-commit-config.yaml

Copied from the adbc repo but limited to what I thought was useful for nanoarrow

Add pre-commit file

---

ci/docker/ubuntu.dockerfile
docs/requirements.txt

chore: Pin sphinx version in documentation builder

---

extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_reader_test.cc

Fix typo in IPC test

---

.gitignore
ci/scripts/build-docs.sh
docs/source/conf.py
docs/source/getting-started/cpp.md
docs/source/getting-started/cpp.rst
docs/source/getting-started/index.rst
docs/source/getting-started/python.rst
docs/source/getting-started/r.rst
docs/source/index.rst
docs/source/python.rst
docs/source/reference/device.rst
docs/source/reference/python.rst
python/src/nanoarrow/__init__.py
python/src/nanoarrow/schema.py

There were a few rough edges:
- Python was not included
- A few sphinx warnings about members that were not found were being ignored
- The READMEs for R and Python are pretty easy to include...I put them under "getting started".

chore(docs): Polish documentation for 0.4.0

---

r/.Rbuildignore
r/NEWS.md
r/README.Rmd
r/README.md
r/cran-comments.md

I'd been doing some of these changes on R packaging branches; however, they belong on main as well!

chore(r): Update NEWS, cran-comments, and README to reflect previous releases

---

dev/release/README.md

As suggested on the dev mailing list!

chore(dev/release): Update release announcement for updated nanoarrow features

---

.github/workflows/python-wheels.yaml

Closes https://github.com/apache/arrow-nanoarrow/issues/427

ci(python): upload nightly python packages

---

python/README.md

Adding missing double quotes so the install with tests works.

[MINOR][Documentation] Fix pip install with test dependencies

---

python/README.ipynb
python/README.md

The previous readme was written for the previous release and is outdated!

docs(python): Update Python bindings readme

---

ci/scripts/build-with-meson.sh
src/nanoarrow/array_test.cc
src/nanoarrow/nanoarrow_ipc_decoder_test.cc
src/nanoarrow/nanoarrow_ipc_reader_test.cc

Figured this is a pretty easy addition, and might help catch more mistakes up front if this becomes a standard CI job

chore(c): Add UBSAN / ASAN to Meson CI job

---

.github/workflows/benchmarks.yaml
.github/workflows/coverage.yaml
.github/workflows/dev.yaml
.github/workflows/docs.yaml
.github/workflows/examples.yaml
.github/workflows/packaging.yaml
.github/workflows/python.yaml
.github/workflows/verify.yaml

chore(ci): update actions/* versions

---

r/NEWS.md

chore(r): Add 0.5.0 NEWS items to R package

---

CMakeLists.txt
examples/cmake-scenarios/CMakeLists.txt
examples/cmake-scenarios/build.sh
examples/cmake-scenarios/src/app.cpp
src/nanoarrow/nanoarrow_device.hpp

fix: Ensure CMake linking against built/installed nanoarrow works for all components

---

src/nanoarrow/ipc/decoder.c
src/nanoarrow/ipc/decoder_test.cc

Before arrow 0.15, encapsulated messages started with just the length instead of with a continuation token

fix: Accommodate IPC messages without continuation bytes

---

ci/scripts/coverage.sh

closes https://github.com/apache/arrow-nanoarrow/issues/670

ci: Fix code coverage for Python library

---

r/R/as-array.R
r/tests/testthat/test-as-array.R

fix(r): sub-day precision Date should be floored when treated as integer

---

dev/release/verify-release-candidate.sh

closes https://github.com/apache/arrow-nanoarrow/issues/678

ci(python): Fix issue with valgrind and Python package

---

.github/workflows/python-wheels.yaml

ci: remove gemfury version pin

---

r/DESCRIPTION

Add missing dplyr dependency

---

src/nanoarrow/common/array.c

typo: valiation->validation

---

src/nanoarrow/ipc/ipc_hpp_test.cc
src/nanoarrow/nanoarrow_ipc.hpp

feat: Add UniqueSharedBuffer C++ wrapper

---

.github/workflows/packaging.yaml
dev/release/rat_exclude_files.txt
dev/release/source_build.sh

https://github.com/apache/arrow-nanoarrow/issues/793

ci: Replace symlinks with files when packaging source

---

src/nanoarrow/common/inline_array.h

Hi there!
I am trying integrate `nanoarrow` into my Zig project. While doing so, the build process failed with an "unreachable code" error. It seems Zig's strict toolchain for importing C headers flags a specific pattern in `src/nanoarrow/common/inline_array.h` as a fatal compile error.
The problematic function appears to be `_ArrowArrayAppendEmptyInternal` , which contains a `for` loop where the inner `switch` statement causes code to be unreachable, which prevents the headers from being imported successfully in Zig.
This PR refactors that loop to remove the explicit `continue` statements and allow control to flow naturally, which resolves the compiler error in Zig without changing the function's logic.
I welcome any feedback or suggestions on this approach. Thank you to the maintainers …

fix(c): Refactor C function to resolve unreachable code error in Zig
