apache/arrow-nanoarrow

CMakeLists.txt
src/nanoarrow/array.c
src/nanoarrow/array_test.cc
src/nanoarrow/nanoarrow.h
src/nanoarrow/typedefs_inline.h

Fixes #5 by implementing an Array whose buffer lifecycle is handled by `struct ArrowBuffer`.

Owning/mutable `struct ArrowArray`

---

src/nanoarrow/metadata.c
src/nanoarrow/metadata_test.cc
src/nanoarrow/nanoarrow.h
src/nanoarrow/schema_view.c
src/nanoarrow/typedefs_inline.h
src/nanoarrow/utils_inline.h

Fixes #6.
This PR adds functions `ArrowMetadataBuilderAppend()` (for blindly but efficiently adding a key/value pair to the end of some metadata) and `ArrowMetadataBuilderSet()` (to less efficiently replace or remove a value for key).
The use case I had in mind is building extension type metadata from some input (i.e., make an output schema like the input except with new extension type or with new serialized extension type metadata). It's rather difficult to replicate the "replace" or "remove" behaviour otherwise.

Add metadata builder functions

---

src/nanoarrow/array_inline.h
src/nanoarrow/array_test.cc
src/nanoarrow/buffer_inline.h
src/nanoarrow/buffer_test.cc
src/nanoarrow/nanoarrow.h

It turns out this is really annoying to do otherwise! Declaring a variable of an appropriate type gets verbose when switching on type, and it sounds like these functions might be useful for database drivers, too.

Buffer element appenders

---

src/nanoarrow/allocator.c
src/nanoarrow/allocator_test.cc
src/nanoarrow/buffer_inline.h
src/nanoarrow/buffer_test.cc
src/nanoarrow/nanoarrow.h
src/nanoarrow/typedefs_inline.h

This feature will allow R/Python runtimes to use the built-in `ArrowArrayInit()`/`ArrowArraySetBuffer()` infrastructure rather than roll their own (e.g., an R package could set a custom deallocator that calls `R_ReleaseObject()` on whatever object was protecting the buffer from garbage collection). Clients that are also using Arrow C++ could use this to with a shared pointer to a Buffer to avoid a copy as well.

Pass the ArrowBufferAllocator by value and implement a custom deallocator

---

src/nanoarrow/nanoarrow_types.h

This is used in ArrowCharView but the include isn't there.

Add missing include in amalgamated build

---

r/configure

On an initial call, `rm` errors when the files are not (yet) present.  Adding `-f` fixes that.   And the final echo has a simple typo.

Make rm call a little more robust, fix typo

---

.github/workflows/examples.yaml
CMakeLists.txt
README.md
examples/cmake-minimal/CMakeLists.txt
examples/cmake-minimal/README.md
examples/cmake-minimal/src/app.c
examples/cmake-minimal/src/library.c
examples/cmake-minimal/src/library.h
examples/vendored-minimal/README.md
examples/vendored-minimal/src/.gitignore
examples/vendored-minimal/src/app.c
examples/vendored-minimal/src/library.c
examples/vendored-minimal/src/library.h
examples/vendored-minimal/src/nanoarrow.c
examples/vendored-minimal/src/nanoarrow.h

Fixes #21. Will demonstrate:
- A minimal CMake configuration that builds + privately links a static nanoarrow build
- A minimal vendored configuration
The principles I'd like to communicate are:
- You must vendor nanoarrow.c/nanoarrow.h or privately link a static library
- You must not expose any parts of nanoarrow.h in one of your library's headers (except the ABI stable Arrow C Data/Stream interface)
- When using the vendored nanoarrow.h/nanoarrow.c version, you should `#define NANOARROW_NAMESPACE SomeNamespace` to avoid symbol collisions (i.e., if somebody else loads your library into the same process or vendors it into another library)
- Maybe bits I'm missing?

Add example usage to examples/ directory

---

.github/workflows/python.yaml
python/.gitignore
python/README.md
python/pyproject.toml
python/setup.py
python/src/nanoarrow/__init__.py
python/src/nanoarrow/_lib.pyx
python/src/nanoarrow/nanoarrow_c.pxd
python/tests/test_nanoarrow.py

This adds a basic package layout and configuration, that can be installed and used as a base to add further functionality to. For testing, I also added a small toy function to convert an arrow array to a numpy array, but to be clear this is not meant as final API.
The current approach here is to use Cython wrapping the nanoarrow dist files.

[Python] Add basic Python package structure and build setup

---

r/configure

This allows `remotes::install_github("apache/arrow-nanoarrow/r")` and `pak::pkg_install("apache/arrow-nanoarrow/r")` to work out-of-the-box without a user having to have cmake installed. This is mostly nice because it allows prototyping of dependencies that have in their DESCRIPTION:
```
Imports: nanoarrow
Remotes: apache/arrow-nanoarrow/r
```
...and nobody has to do anything special to install the nanoarrow dependency. Note that the previous way to make this work was `remotes::install_github("apache/arrow-nanoarrow/r", build = FALSE)`, which does a straight `R CMD INSTALL` instead of an `R CMD build` + `R CMD INSTALL`.

[R] Make installation work with default args to `remotes::install_github()`/`pak::pkg_install()`

---

src/nanoarrow/nanoarrow.h
src/nanoarrow/nanoarrow.hpp
src/nanoarrow/nanoarrow_types.h

This was causing old versions of doxygen to capitalize defgroup names, causing breathe not to be able to find them!

[Documentation] Add missing group titles

---

src/nanoarrow/array.c
src/nanoarrow/array_inline.h
src/nanoarrow/array_test.cc

Generally, make sure MAP is consistent with LIST:
- MAP has 2 buffers (validity + offset)
- MAP must be finished like LIST (we could go further and have FinishElement also finish the child in the case of MAP, since we know it must always be STRUCT)

[C] Fix some MAP type support issues

---

src/nanoarrow/array_inline.h
src/nanoarrow/array_test.cc

[C] Fix AppendDouble to accept all values on float arrays

---

examples/cmake-minimal/src/library.c
examples/vendored-minimal/src/library.c
r/src/array_view.c
r/src/convert.c
src/nanoarrow/array.c
src/nanoarrow/array_inline.h
src/nanoarrow/array_stream_test.cc
src/nanoarrow/array_test.cc
src/nanoarrow/nanoarrow.h
src/nanoarrow/nanoarrow.hpp
src/nanoarrow/nanoarrow_hpp_test.cc
src/nanoarrow/schema.c
src/nanoarrow/schema_test.cc

Will address part of #73 (simplifies creating map, union, and list schemas).
This PR updates the syntax for initializing `ArrowSchema`s to better support lists, unions, and maps. Before this PR, you had to create these schemas by hand (i.e., setting the `format` string and and allocating children yourself). After this PR, the syntax for a list would be:
```c
struct ArrowSchema schema;
ArrowSchemaInit(&schema);
ArrowSchemaSetType(&schema, NANOARROW_TYPE_LIST);
ArrowSchemaSetType(schema.children[0], NANOARROW_TYPE_INT32);
```
...for a `map <int32, string>` would be:
```c
struct ArrowSchema schema;
ArrowSchemaInit(&schema);
ArrowSchemaSetType(&schema, NANOARROW_TYPE_MAP);
ArrowSchemaSetType(schema.children[0].children[0], NANOARROW_TYPE_INT32); …
```

[C] Adapt ArrowSchema initialization to better support recursive types

---

r/src/schema.c
src/nanoarrow/array.c
src/nanoarrow/array_inline.h
src/nanoarrow/array_test.cc
src/nanoarrow/nanoarrow.h
src/nanoarrow/nanoarrow_types.h
src/nanoarrow/schema.c
src/nanoarrow/schema_test.cc

Adds support for dense and sparse unions in `ArrowArrayAppendNull()` and `ArrowArrayFinishUnionElement()` for #73. Some things I'm not sure about:
- Do we need to support non-standard union IDs in append mode? I don't have a good example of a Union with non-standard TypeIDs on hand and I'm still fuzy on the correct behaviour there.
- Am I constructing the Sparse Union from C++ properly? It seems like I have to manually append to each child which I didn't expect to have to do.
- Is there anything else about Unions that I'm missing?

[C] Union Appender support

---

src/nanoarrow/array.c
src/nanoarrow/array_inline.h
src/nanoarrow/array_test.cc
src/nanoarrow/nanoarrow.h
src/nanoarrow/nanoarrow_types.h

Ok, I think this has everything one would need to inspect union types without having to remember the spec. Given a valid union schema, one can:
```c
ArrowArrayViewInitFromSchema(&array_view, &schema, nullptr);
int8_t child_index = ArrowArrayViewUnionChildIndex(&array_view, i);
int64_t child_offset = ArrowArrayViewUnionChildOffset(&array_view, i);
// Figure out which accessor you need. If it's an int, you could
struct ArrowArrayView* child = array_view.children[child_index];
ArrowArrayViewGetIntUnsafe(child, child_offset);
```
Fixes #73.

[C] Add read support for unions in the `ArrowArrayView`

---

.github/workflows/build-and-test.yaml
.github/workflows/docs.yaml
.github/workflows/examples.yaml
.github/workflows/python.yaml
.github/workflows/r-check.yaml
.github/workflows/verify-source.yaml

Installing R dependencies takes the majority of the time in the verification action...using the dependencies action will install them in advance and maintain a cache so that this hopefully doesn't take as long.

[CI] Prefetch/cache R package testing dependencies

---

r/DESCRIPTION
r/README.Rmd
r/README.md
r/configure.win

Before this PR, `remotes::install_github("apache/arrow-nanoarrow/r")` and `pak::pak("apache/arrow-nanoarrow/r")` would fail on Windows because on Windows `configure` isn't run by RTools even for source builds ( https://github.com/pola-rs/r-polars/pull/5#issuecomment-1378755004 ).

[R] Make sure `remotes::install_github()` works on Windows

---

.github/workflows/packaging.yaml
CHANGELOG.md
NOTICE.txt
dev/release/01-prepare.sh
dev/release/02-sign.sh
dev/release/03-source.sh
dev/release/check-rat-report.py
dev/release/post-01-upload.sh
dev/release/post-02-bump-versions.sh
dev/release/rat_exclude_files.txt
dev/release/run-rat.sh
dev/release/source_build.sh
dev/release/utils-prepare.sh
r/.covrignore
r/.gitignore
r/R/altrep.R
r/R/type.R
r/_pkgdown.yml
r/src/pointers_cpp.cc
r/tests/testthat/test-altrep.R
r/tests/testthat/test-type.R

Closes #95.
I don't think this is *everything* that is needed for release but I think it is close! There is still a few features that are needed in the R package before a release candidate can go out, but I want to make sure that enough of the infrastructure is in place that generating the release candidate isn't the hold up.

chore: Port release infrastructure from ADBC

---

.github/workflows/build-and-test.yaml
CMakeLists.txt
src/nanoarrow/array_stream.c
src/nanoarrow/utils.c

Apparently it's difficult to pass different flags to C and C++ files in a Python extension. The C library was almost valid C++ anyway and because there are quite a few static inline functions, it's probably a good idea to make sure that the project compiles under a C++ compiler as well (since the nanoarrow.h header will be compiled with C++ if included in a C++ project).

fix: make sure bundled nanoarrow is also valid C++

---

r/tests/testthat/test-pkg-arrow.R
r/tests/testthat/test-schema.R
r/tests/testthat/test-util.R

...mostly Docker images that are slow or are missing components usually present on systems people are actually using.
- Closes #121 
- Closes #123

fix: Improve reliability of R tests on non-standard systems

---

src/nanoarrow/array_test.cc

fix: `isnan()` usage compatible with old clang

---

CMakeLists.txt
dev/release/verify-release-candidate.sh

Before this PR, any invocation of cmake build + test and/or running the verification script fails on Windows because (1) the most common R executable path has a space (`C:/Program Files/R/...`) and because dynamically linking Arrow is hard.

fix: Fix cmake build + test and verification script on Windows

---

.github/workflows/r-check.yaml
r/DESCRIPTION
r/tests/testthat/test-altrep.R
r/tests/testthat/test-array.R
r/tests/testthat/test-convert-array-stream.R
r/tests/testthat/test-convert-array.R
r/tests/testthat/test-infer-ptype.R
r/tests/testthat/test-util.R
src/nanoarrow/array.c
src/nanoarrow/nanoarrow.h
src/nanoarrow/schema.c
src/nanoarrow/utils.c

fix: Explicit `stringsAsFactors = FALSE` for R <= 3.6

---

r/src/buffer.c

fix(r): Don't memcpy NULL when converting buffer to raw

---

extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc.c
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc.h
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_test.cc

This PR tweaks the tests and endianness setup so that the tests pass on big endian. Buffer decoding on non-platform endian isn't supported yet...this PR is just about making sure all of the other infrastructure around the buffers works. This is also in preparation for adding the nanoarrow_ipc extension to release verification (which now runs on big endian on CI).
You can test this using the shiny new alpine-s390x image in this repo's container store!
```bash
mkdir build && cd build
cmake ..
cmake --build .
ctest
```

fix(extensions/nanoarrow_ipc): Ensure tests pass on big endian

---

extensions/nanoarrow_ipc/CMakeLists.txt
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc.h
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder.c
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder_test.cc
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_reader.c
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_reader_test.cc

This PR makes buffer construction more flexible, with the initial target being zero-copy shared references to a single `struct ArrowBuffer` containing the read-in message body. Where supported (i.e., C11 and up), these shared buffer references are thread safe.
I implemented this by abstracting out a `struct ArrowIpcBufferFactory`. This could be exposed to the user, too (but maybe in another PR where I also implement endian swapping).
Using the decoder API, you can request this using a new function:
```c
ArrowErrorCode ArrowIpcDecoderDecodeArrayFromOwned(struct ArrowIpcDecoder* decoder,
struct ArrowBuffer* body, int64_t i,
struct ArrowArray* out,
struct ArrowError* error);
```
Using the `ArrowArrayStream` interface this is the default *if* shared buffers are thread safe (this can be …

feat(extensions/nanoarrow_ipc): Allow shared buffers for zero-copy buffer decode

---

r/src/as_array.c
r/tests/testthat/test-as-array.R
r/tests/testthat/test-convert-array.R

Closes #159.
Checked via:
```bash
PKG_CFLAGS=-fsanitize=undefined PKG_LIBS=-fsanitize=undefined R CMD INSTALL . --preclean
```
Then:
```r
devtools::test()
```

fix(r): Don't invoke undefined behaviour in conversions to/from Arrow

---

extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_reader.c

Before this PR, the input was released from within `get_next()` in the `ArrowArrayStream` implementation. This is unnecessary and prevented the reader from being useful in the context of streams that have non-standard layouts (e.g., if several streams are concatenated together, one could continue calling `get_next()` to "try again"). Also, there is a much better chance that `get_next()` is going to get called on another thread and it's easier to reason about lifecycles if the stream gets closed on `release()` instead.

fix(extensions/nanoarrow_ipc): Don't release input stream automatically on end of input

---

.github/workflows/docker-build.yaml
ci/docker/centos7.dockerfile
ci/docker/ubuntu.dockerfile

...so that we can run memcheck from docker compose and at least one image runs nanoarrow/R tests with arrow/R installed.

chore(ci): Add centos7 image; add valgrind and arrow/R to ubuntu image

---

src/nanoarrow/array.c
src/nanoarrow/array_inline.h
src/nanoarrow/array_test.cc
src/nanoarrow/nanoarrow.h
src/nanoarrow/nanoarrow_types.h

This is required for IPC reading because corrupted offset and/or union type ID buffers could result in consumers accessing out-of-bounds elements. `ArrowArrayViewSetArray()` already checked the *last* element of offset buffers against lengths but didn't check the first element and didn't check for negative sequential offsets.

feat: Implement `ArrowArrayViewValidateFull()`

---

README.md
examples/cmake-minimal/src/library.c
examples/vendored-minimal/src/library.c
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder.c
r/src/array.c
r/src/as_array.c
src/nanoarrow/array.c
src/nanoarrow/array_stream_test.cc
src/nanoarrow/array_test.cc
src/nanoarrow/nanoarrow.h
src/nanoarrow/nanoarrow_hpp_test.cc
src/nanoarrow/nanoarrow_types.h

This is a breaking change! The signature of `ArrowArrayFinishBuilding()` gains a `validation_level` argument, and the original function was renamed to `ArrowArrayFinishBuildingDefault()`. I could do this in a non-breaking way but there are no non-awkward names for `ArrowArrayFinishBuildingWithExplicitValidationLevel()` and it seems more important to cultivate a quality API at this point rather than maintain full backward compatibility (plus it's a relatively easy rename fix).
This adds two important features. First, it lets you preform more validation if you want to (via `NANOARROW_VALIDATION_LEVEL_FULL`, implemented with the just-added `ArrowArrayViewValidateFull()`). Second, it lets you perform less validation if you want to (e.g., if your buffers are sitting on a GPU and dereferencing …

feat!: Allow explicit validation level in `ArrowArrayFinishBuilding()`

---

.github/workflows/verify.yaml
CMakeLists.txt
dev/release/rat_exclude_files.txt
dev/release/source_build.sh
dev/release/verify-release-candidate.sh
extensions/nanoarrow_ipc/CMakeLists.txt
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_reader_test.cc

This PR:
- Adds the IPC extension to the release verification
- Adds a memcheck option to release verification (off by default)
- Adds the IPC extension to the source tarball now that it's being verified
- Adds arm64, memcheck, and centos7 to the CI configuration that runs the verification script (with bundling checks turned off for anything that runs on qemu)

chore: Add IPC extension and ARM64 to verification script

---

src/nanoarrow/array_inline.h
src/nanoarrow/array_test.cc
src/nanoarrow/nanoarrow.h
src/nanoarrow/nanoarrow_types.h
src/nanoarrow/utils_test.cc

Closes #170.
This is not designed to be a fully-featured performant decimal math library, but is designed to help with byte shuffling and provide enough support that users can write tests for decimal arrays (e.g., by providing integer getters and setters for numbers that fit within the int64 range).
Adds a `struct ArrowDecimal` and utility functions:
```c
static inline void ArrowDecimalInit(struct ArrowDecimal* decimal, int32_t bitwidth,
int32_t precision, int32_t scale);
static inline int64_t ArrowDecimalGetIntUnsafe(struct ArrowDecimal* decimal);
static inline void ArrowDecimalGetBytes(struct ArrowDecimal* decimal, uint8_t* out);
static inline int64_t ArrowDecimalSign(struct ArrowDecimal* decimal);
static inline void ArrowDecimalSetInt(struct ArrowDecimal* decimal, int64_t value); …
```

feat: Add Decimal Get/Set utilities

---

ci/docker/ubuntu.dockerfile

Missing a few that allow pkgdown to install and build the documentation.

chore(ci): Add more system libs to Ubuntu image

---

.github/workflows/docs.yaml
.github/workflows/examples.yaml
ci/scripts/build-docs.sh
docs/.gitignore
docs/source/getting-started.md
docs/source/getting-started.rst
examples/linesplitter/CMakeLists.txt
examples/linesplitter/linesplitter.cc
examples/linesplitter/linesplitter.h
examples/linesplitter/linesplitter_test.cc

This PR adds a "getting started" tutorial. The basic premise is that it demonstrates building a library in C++ that exposes an Arrow-based API...in the future, one could add tutorials for wrapping it in R and Python as well.
Open to any and all feedback (including a different premise!)

docs: Add "getting started with nanoarrow" tutorial

---

r/R/as-array.R
r/src/array_stream.c
r/src/as_array.c
r/src/convert_array.c
r/src/infer_ptype.c
r/src/materialize.c
r/src/schema.h
r/tests/testthat/test-as-array.R

Needed to support all the types that ADBC might return (see https://github.com/r-dbi/adbc/discussions/4 ). This currently returns unions as `data.frame()` with NA values (basically a sparse union equivalent for R). There are certainly other ways to represent that in R (maybe just a `list()`). R/nanoarrow models conversions in both directions as many <-> many, so a future PR could implement `as_nanoarrow_array(list(), schema = na_sparse|dense_union()` and/or `convert_array(union_array, list())`.
``` r
dense_union <- as_nanoarrow_array(
data.frame(dbl = c(NA, 2), chr = c("one", NA)),
schema = na_dense_union(list(dbl = na_double(), chr = na_string()))
)
sparse_union <- as_nanoarrow_array(
data.frame(dbl = c(NA, 2), chr = c("one", NA)),
schema = na_sparse_union(list(dbl = …
```

feat(r): Union array support

---

src/nanoarrow/array_inline.h
src/nanoarrow/array_test.cc

Similar to what exists for Dense/Sparse Union. This would at least be useful in the ADBC library, which currently provides its own implementation
https://github.com/apache/arrow-adbc/pull/679#discussion_r1195786712

feat: Add `ArrowArrayViewListChildOffset()`

---

r/tests/testthat/test-schema.R

Seen on my system with `options(warnPartialMatchDollar = TRUE)` .

chore(r): Fix partial matching warning in tests

---

dist/nanoarrow.c
src/nanoarrow/array.c

In `ArrowArrayAllocateChildren()` two loops over all children follow each other directly.  The first assigns a NULL to each element, then second overwrites that with an allocation.  That makes the first loop effectively deadweight.  It may be there on purpose in which case you just disregard and close this PR.  But if it is an oversight this will make it ever-so-marginally faster as we can skip one loop over `n_children`.
(I noticed another microscopic style difference:  in the corresponding `ArrowSchemaAllocateChildren()` an `if (n_children != 0) {...}` wraps around the core code of function; there it is a simpler `if (n_children == 0) return ...`.  Of course they are also the same "in practice" and I don't have a style preference either -- just curious that they differ.  No need for …

fix: Improve readability of `ArrowArrayAllocateChildren()`

---

r/R/array-stream.R
r/tests/testthat/test-array-stream.R

In https://github.com/apache/arrow-adbc/pull/706 , the added `read_adbc()` releases a stream whose statement (and possibly connection) will be released when the stream itself is released. When the user is definitely consuming the entire stream, it is helpful to release it at a guaranteed time so that subsequent operations (e.g., closing a connection, deleting a file on Windows) don't confusingly fail.

fix(r): Release streams when calling `as.vector()` or `as.data.frame()`

---

r/R/as-array.R
src/nanoarrow/array.c
src/nanoarrow/array_inline.h
src/nanoarrow/array_test.cc
src/nanoarrow/nanoarrow.h
src/nanoarrow/nanoarrow_types.h

The initial motivation for this refactor was to make it possible to go straight from Arrow IPC to ArrowArrayView with zero heap allocations and improve IPC validation; however, the changes needed for that (basically, give every ArrowArrayView its own offset, length, and null_count) allowed unifying the validation that we do when building arrays and the validation we do when wrapping a foregin ArrowArray in an ArrowArrayView. This PR ensures that no internal ArrowArrayView functions actually refer to the `array` member since there is no guarantee that an ArrowArray backs the buffers. Along the way, error messages and documentation were improved.

refactor: Unify `ArrowArrayView` and `ArrowArray` validation

---

src/nanoarrow/nanoarrow.hpp
src/nanoarrow/nanoarrow_hpp_test.cc

fix: clear `release` in `EmptyArrayStream::release_wrapper`

---

.github/workflows/docker-build.yaml
ci/docker/alpine.dockerfile
ci/docker/archlinux.dockerfile
ci/docker/centos7.dockerfile
ci/docker/fedora.dockerfile
ci/docker/ubuntu.dockerfile

s390x was failing because it was running `docker compose build` and there are now some compose jobs that aren't intended to run on s390x (e.g., documentation, coverage). Python build tools aren't essential yet but will be at some point and updating the images is a bit of a pain.

chore(ci): Add Python packaging tools to images + fix s390x build

---

dist/nanoarrow.c
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc.h
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder.c
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder_test.cc
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_reader.c
src/nanoarrow/array.c
src/nanoarrow/array_test.cc
src/nanoarrow/nanoarrow.h

Currently the decoder always assembles an `ArrowArray` and subsequently validates that array. That caused a problem when validating a union because the `ArrowArray` builder doesn't have a place to put custom type IDs. Also, this is every so slightly wasteful: the `ArrowArray` validation allocates an unnecessary `ArrowArrayView` and validates that. We already have an `ArrowArrayView` to help with the buffer shuffling, so this PR just swaps the direction: the first step is to create the `ArrowArrayView`; the second step is to validate the `ArrowArrayView`, then populate the `ArrowArray` (if requested).
Closes #178 by erroring if there is insufficient information to validate a union array. I don't think this will cause problems with existing code that builds a union array but if it does it …

refactor(extensions/nanoarrow_ipc): Reconfigure assembling arrays for better validation

---

r/R/convert-array-stream.R
r/tests/testthat/test-convert-array-stream.R

fix(r): Fix `convert_array_stream()` for non-record batch stream with zero batches

---

extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder.c
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder_test.cc
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_files_test.cc
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_reader_test.cc

Ensures IPC reader compatibility reading little endian streams from big endian (99% for the purposes of not scaring away potential dependencies that run tests on big endian). It's also not that hard to do since flatcc did the hard work of defining `bswap16()`, `bswap32()`, and `bswap64()` based on compiler defines.

feat(extensions/nanoarrow_ipc): Add endian swapping to IPC reader

---

r/R/array.R
r/src/array.c
r/src/array.h
src/nanoarrow/array.c
src/nanoarrow/array_inline.h
src/nanoarrow/array_test.cc
src/nanoarrow/nanoarrow.h
src/nanoarrow/nanoarrow_types.h

This doesn't add any features really, but ensures that one can walk `ArrowSchema`, `ArrowArray`, and `ArrowArrayView` recursively using the same pattern. I'd like to include this in the 0.2 release because it is very difficult to work around this limitation: for example, if you have a deeply nested dictionary field, you currently have to walk your whole tree of arrays twice (once to validate the non-dictionary bits, once looking for dictionary bits that may or may not exist to validate). The R package worked around this in some creative but error-prone ways and I'd like to avoid anybody else attempting creative workarounds when this is a feature that will almost certainly get added soon.
Another application of this is device array support, since that PR essentially constructs an …

feat: Include dictionary member in `ArrowArrayView` struct

---

extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder.c

This only affects Arrow C++ <= 9.0.0 consumers (i.e., the last Arrow C++ that builds with default Centos 7 compilers and the version that exists on archlinux when you install from the system package manager). Technically it adds a redundant check when producing an Array; however, that check is cheap and the way to maximize performance would be to completely avoid the Array in the first place.
Fixes verification failure on Centos 7 and Archlinux: https://github.com/apache/arrow-nanoarrow/actions/runs/5232667457/jobs/9447554040 , https://github.com/apache/arrow-nanoarrow/actions/runs/5232667457/jobs/9447553922 , as tested by `export NANOARROW_PLATFORM=centos7 && docker compose run --rm verify`.

fix(extensions/nanoarrow_ipc): Don't produce arrays with NULL data buffers

---

.github/workflows/verify.yaml

chore: Update Arrow C++ version for Windows verification and remove rtools from PATH on Windows

---

ci/docker/ubuntu.dockerfile
dev/release/verify-release-candidate.sh
valgrind.supp

As reported in #200, when loading the arrow R package and allocating at least once there can be an additional thread local storage allocation by jemalloc that leaks. I wasn't able to replicate this in Docker (ubuntu:22.04 or debian:testing, which I believe is the platform CRAN uses); however, their appearance shouldn't cause nanoarrow's memcheck to fail (R or otherwise).
In trying to replicate this, I also realized that release verification wasn't running the R tests with valgrind. On CI this isn't possible because we install arrow from RSPM and that build crashes R under valgrind for some reason. The verification job happens on Docker, though, so we can add the check there.
Closes #200.

chore: Suppress more jemalloc thread local storage possible leaks and add memcheck for R to verification

---

r/bootstrap.R

It was "CMAKE" but should have been "CMAKE_BIN".
Closes #223.

chore(r): Fix environment variable used to denote the location of cmake

---

src/nanoarrow/array_inline.h
src/nanoarrow/nanoarrow_types.h

`value` within this function is a uint64_t, so using the CHECK_RANGE macro yields warnings/errors like:
```sh
/home/willayd/clones/arrow-adbc/c/vendor/nanoarrow/nanoarrow.h:192:31: error: comparison of unsigned expression in ‘>= 0’ is always true [-Werror=type-limits]
192 |   NANOARROW_RETURN_NOT_OK((x_ >= min_ && x_ <= max_) ? NANOARROW_OK : EINVAL)
|                               ^
/home/willayd/clones/arrow-adbc/c/vendor/nanoarrow/nanoarrow.h:187:23: note: in definition of macro ‘_NANOARROW_RETURN_NOT_OK_IMPL’
187 |     const int NAME = (EXPR);                      \
|                       ^~~~
/home/willayd/clones/arrow-adbc/c/vendor/nanoarrow/nanoarrow.h:192:3: note: in expansion of macro ‘NANOARROW_RETURN_NOT_OK’
192 |   NANOARROW_RETURN_NOT_OK((x_ >= min_ && x_ <= max_) ? …
```

fix: Improve limit check for unsigned input

---

.github/workflows/python.yaml

Small follow-up on https://github.com/apache/arrow-nanoarrow/pull/117/files#r1231696846

ci(python): avoid reinstalling for testing docstrings

---

README.md

While integrating into another C project, I pulled example code from the readme that called,
```c
ArrowSchemaInit(schema_out, NANOARROW_TYPE_INT32))
```
and got this error:
```
src/main.c:41:57: error: too many arguments to function call, expected single argument 'schema', have 2 arguments
NANOARROW_RETURN_NOT_OK(ArrowSchemaInit(schema_out, NANOARROW_TYPE_INT32));
```

Fix incorrect function name in README

---

ci/docker/archlinux.dockerfile

I'd added some Python dependencies to all the dev docker images in preparation for actually verifying the Python builds; however the archlinux dev container build was failing because `pip` is not allowed on that platforms. This PR replaces the `pip` command with Archlinux-supplied Python dependencies.

chore: Fix archlinux dev docker container build

---

.github/workflows/verify.yaml

Previously this was installing from `apt` on Ubuntu and `brew` on MacOS; however, the Windows verification was much faster because the arrow install can be cached. Additionally, the MacOS build was failing due to something protobuf-related and the minimal build solves that problem too.

chore: Update verification action to use a cached Arrow C++ build on all platforms

---

python/src/nanoarrow/_lib.pyx

After https://github.com/apache/arrow-nanoarrow/pull/262#discussion_r1269088588 .

refactor(python): Cleaner strategy for `__iter__()` on an `ArrowArrayStream`

---

ci/docker/centos7.dockerfile

On Centos7/arm64, building numpy from source is required; however, the build fails with Cython 3. This PR sets an upper pin on the Cython version specifically on centos7.

chore: Set upper pin on Cython on centos7

---

r/R/array.R
r/man/as_nanoarrow_array.Rd

These pages were renamed as part of the 13.0.0 release and will cause submission problems for arrow's reverse dependency checks (since the page removal causes the CMD check to fail).

fix(r): Don't link to arrow package R6 class pages

---

src/nanoarrow/array_inline.h
src/nanoarrow/array_test.cc

Follow on to https://github.com/apache/arrow-nanoarrow/pull/258

Add ArrowArrayViewGetIntervalUnsafe

---

src/nanoarrow/array_inline.h
src/nanoarrow/nanoarrow.h
src/nanoarrow/nanoarrow_types.h
src/nanoarrow/schema.c

I am attempting to vendor nanoarrow into pandas (see https://github.com/pandas-dev/pandas/pull/54506) 
We use codespell in our pre-commit and it is failing due to these. https://github.com/codespell-project/codespell
Could also add to pre-commit here if there is interest

chore: Typo Fixup

---

docker-compose.yml

Before, running `docker compose run --rm docs` crashed because `pandoc` doesn't work with docker's emulation for whatever reason. Now that the manifest image works, we can use it for those types of workflows (I left out verify because that one should pretty much always be platform-specific).

chore: Use manifest ubuntu image for non-platform specific compose services

---

.asf.yaml
.github/workflows/docs.yaml
README.md
r/README.Rmd
r/README.md

Now that the documentation is hosted at https://arrow.apache.org/nanoarrow via the asf-site branch, the dev documentation should be there, too.

chore: Publish dev docs to asf-site branch instead of gh-pages

---

r/src/materialize_int.h
r/src/materialize_lgl.h
src/nanoarrow/buffer_inline.h
src/nanoarrow/buffer_test.cc
src/nanoarrow/nanoarrow.h

As a follow-up to #276. The `int32` version is useful because R uses 32-bit integers to represent boolean (i.e., logical) arrays. This results in a significant speedup in boolean conversion!
@WillAyd: I updated a few things that you *just* added (Sorry! 😬 ):
- I changed `Bitmap` -> `Bits` and removed `Unsafe` to make it more consistent with the other functions that accept `const uint8_t* bits`
- I updated the test function so that it tests both the int32 and int8 types at once
Before this PR:
``` r
lgls <- nanoarrow:::vec_gen(logical(), 1e6)
bool_array <- as_nanoarrow_array(lgls)
bool_array_arrow <- arrow::as_arrow_array(bool_array)
bench::mark(
convert_array(bool_array, logical()),
as.vector(bool_array_arrow),
as.logical(lgls)
)
#> # A tibble: 3 × 6
#>   expression …
```

feat: Add `ArrowBitsUnpackInt32()`

---

r/R/infer-ptype.R

Closes #281.
``` r
library(adbcdrivermanager)
db <- adbc_database_init(adbcsqlite::adbcsqlite(), uri = ":memory:")
con <- adbc_connection_init(db)
stream <- adbc_connection_get_info(con, 0)
tibble::as_tibble(stream)
#> # A tibble: 1 × 2
#>   info_name info_value$string_value $bool_value $int64_value $int32_bitmask
#>       <dbl> <chr>                   <lgl>              <dbl>          <int>
#> 1         0 SQLite                  NA                    NA             NA
#> # ℹ 2 more variables: info_value$string_list <list<chr>>,
#> #   $int32_to_int32_list_map <list<df[,2]>>
```
<sup>Created on 2023-08-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

fix(r): Support map conversion to R vector

---

extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder.c
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder_test.cc
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_reader.c
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_reader_test.cc

Closes #287.
The reported crash occurred because the internal `ArrowIpcDecoderVerifyHeader()` incorrectly interpreted the return value of `ArrowIpcDecoderCheckHeader()`. Because the header checker returned an error code sometimes even if it succeeded, we had been ignoring the error in `ArrowIpcDecoderVerifyHeader()` which resulted in issuing commands like `memcpy(dst, src, -8)`. I believe that's undefined behaviour, leading to the intermittent nature of the crash.
In adding tests for this kind of error, I also made some improvements to error messages along the way.
```bash
cd /arrow-nanoarrow/extensions/nanoarrow_ipc
mkdir build && cd build
cmake .. -DNANOARROW_IPC_BUILD_APPS=ON
curl https://gist.githubusercontent.com/amoeba/b64fc94ba5224bafcb3734bd261181d5/raw/af4c93da7ce6affba74a80e1ba94 …
```

fix(extensions/nanoarrow_ipc): Fix crash and mixleading error messages resulting from corrupted streams

---

src/nanoarrow/array.c
src/nanoarrow/array_test.cc

Closes #290.
This PR fixes the check for increasing offsets: previously it calculated a diff between pairs of elements and ensured that the value was > 0. This failed for expressions like `int32_t diff = (int32_t)-2147483648 - (int32_t)2080374784`, where because of overflow, `diff` evalutes to `> 0`.

fix: Ensure that test for increasing offsets is not affected by overflow

---

r/src/materialize_dbl.h
r/tests/testthat/test-convert-array.R

It looks like I had left this as a TODO after my initial push to get most conversions implemented. The idea is to warn when converting very large int64/uint64 values to double. This an important case to warn for because double is the default conversion from int64 and values that won't (or might not) roundtrip back to int64 are important to warn about. See #293 implementing a safer conversion.
``` r
array <- as_nanoarrow_array(2^54, schema = na_int64())
convert_array(array, double())
#> Warning in convert_array.default(array, double()): 1 value(s) may have incurred
#> loss of precision in conversion to double()
#> [1] 1.80144e+16
```
<sup>Created on 2023-09-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

fix(r): Warn for possibly out of range int64 -> double conversions

---

r/R/util.R
r/src/as_array.c
r/src/materialize_common.h
r/src/materialize_dbl.h
r/src/materialize_int.h
r/src/materialize_int64.h
r/src/materialize_unspecified.h
r/tests/testthat/test-as-array.R
r/tests/testthat/test-convert-array.R

This lets a caller take appropriate action (or give an error, or give a better warning) if a lossy conversion occurs.
Closes #297.
``` r
array <- as_nanoarrow_array(2^54, schema = na_int64())
convert_array(array, double())
#> Warning in convert_array.default(array, double()): 1 value(s) may have incurred
#> loss of precision in conversion to double()
#> [1] 1.80144e+16
withCallingHandlers(
convert_array(array, double()),
nanoarrow_warning_lossy_conversion = function(x) {
warning(
"This is a better explanation of what happened!",
call. = conditionCall(x)
)
tryInvokeRestart("muffleWarning")
}
)
#> Warning in (function (x) : This is a better explanation of what happened!
#> [1] 1.80144e+16
```
<sup>Created on 2023-09-18 with [reprex …

feat(r): Use classed warnings to signal that a lossy conversion occurred

---

r/R/type.R
r/tests/testthat/test-type.R

Closes #296.
``` r
arrow::as_data_type(na_dictionary(na_string(), ordered = FALSE))
#> DictionaryType
#> dictionary<values=string, indices=int32>
arrow::as_data_type(na_dictionary(na_string(), ordered = TRUE))
#> DictionaryType
#> dictionary<values=string, indices=int32>
arrow::as_data_type(
infer_nanoarrow_schema(factor(letters[1:5], ordered = TRUE))
)
#> DictionaryType
#> dictionary<values=string, indices=int32>
arrow::as_data_type(
infer_nanoarrow_schema(factor(letters[1:5], ordered = FALSE))
)
#> DictionaryType
#> dictionary<values=string, indices=int32>
```
<sup>Created on 2023-09-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

fix(r): Ensure `ordered` is reflected in `na_dictionary()`

---

src/nanoarrow/buffer_test.cc

fix: Fix declaration of an array with an ambiguously constexpr size

---

CMakeLists.txt
CMakeUserPresets.json.example

fix(dev/release): Increase test discovery timeout value

---

src/nanoarrow/array_inline.h
src/nanoarrow/array_test.cc
src/nanoarrow/nanoarrow.h

This aligns nanoarrow with the behaviour in the ADBC postgres driver. It is useful to differentiate this case because frequently a caller will want to finish the current array and start a new one with the new value.

fix: Return `EOVERFLOW` when appending to a string or binary type would exeed 2 GB

---

r/_pkgdown.yml

Since the R package is in a subdirectory, I believe this setting is necessary to ensure that the links to the source files are generated correctly.

docs(r): fix source links from pkgdown site

---

python/src/nanoarrow/_lib.pyx
python/src/nanoarrow/lib.py
python/tests/test_capsules.py

First commit with just importing for now. Will do exporting next.

feat(python): Support the PyCapsule protocol

---

src/nanoarrow/nanoarrow_testing.hpp
src/nanoarrow/nanoarrow_testing_test.cc

Adds methods to the `TestingJSONWriter` to write `Schema`, `Field`, and `Type`. There are some unsupported types but I'd like to get some end-to-end bits working before rounding out type support!

feat: Add Type/Field/Schema JSON writer for integration testing JSON

---

r/src/materialize.c
src/nanoarrow/array.c
src/nanoarrow/array_inline.h
src/nanoarrow/array_stream.c
src/nanoarrow/nanoarrow.h
src/nanoarrow/nanoarrow_types.h
src/nanoarrow/schema.c

A number of functions accept pointers (e.g., `ArrowSchema*`) but do not take ownership of the argument or modify it in any way. To better communicate this, this PR adds `const` before all possible parameters that are not modified by the function.
Closes #215.

fix: Add `const` qualifier where appropriate in struct fields and declarations

---

r/src/array_stream.c

Uncovered when investigating https://github.com/apache/arrow-adbc/issues/1348 and https://github.com/apache/arrow-adbc/pull/1334 . Before, the release callback was getting called by the garbage collector (so no memory leak was reported); however, the order of the array stream finalizer and the user-supplied R finalizer was non-deterministic based on when the garbage collector ran.

fix(r): Ensure wrapper array stream eagerly releases the wrapped array stream

---

ci/scripts/coverage.sh
extensions/nanoarrow_ipc/CMakeLists.txt
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_files_test.cc

This PR adds a "golden file" integration test to the existing suite of tests that read files from the arrow-testing repo. The existing test read the IPC stream file using nanoarrow's IPC reader and Arrow C++'s IPC reader and used Arrow C++ to check equality. The added test is more similar to the golden file test described in the integration testing section of the documentation (read IPC, read testing JSON, use nanoarrow testing utils to check equality). This involved some refactoring to re-use the infrastructure properly for both types of tests.
Originally I wrote a dedicated executable and some bash to do these kinds of tests ( https://gist.github.com/paleolimbot/ec2a2067198f0de1901c107c783d3b26 ); however, integrating it into the existing tests is cleaner and makes it easier to run them …

chore(extensions/nanoarrow_ipc): Add golden file testing JSON tests to existing arrow-testing tests

---

extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc.hpp
src/nanoarrow/nanoarrow.hpp
src/nanoarrow/nanoarrow_hpp_test.cc

An early commit implemented `nanoarrow::EmptyArrayStream` and `nanoarrow::VectorArrayStream` in the nanoarrow.hpp C++ helpers. The intention at the time was to make it "easy"/idiomatic to use a C++ object to back an `ArrowArrayStream`; however, it was in practice difficult to actually make work (I tried briefly and gave up when writing a [dummy ADBC driver](https://github.com/voltrondata-labs/blog-posts-code/blob/main/2023-08-nanoarrow-adbc/simple_csv_reader.cc#L52-L177) for [this blog post](https://voltrondata.com/resources/nanoarrow-lightweight-embeddable-arrow-implementation-data-pipelines).
This PR deprecates the original syntax and migrates it to the following.
Implementation:
```cpp
class StreamImpl {
public:
// Public methods (e.g., constructor) used from C++ to initialize relevant …
```

refactor: Improve syntax for implementing `ArrowArrayStream` from C++

---

.github/workflows/build-and-test.yaml
docs/source/getting-started.md
extensions/nanoarrow_device/src/nanoarrow/nanoarrow_device.c
extensions/nanoarrow_device/src/nanoarrow/nanoarrow_device.hpp
extensions/nanoarrow_device/src/nanoarrow/nanoarrow_device_cuda.c
extensions/nanoarrow_device/src/nanoarrow/nanoarrow_device_cuda_test.cc
extensions/nanoarrow_device/src/nanoarrow/nanoarrow_device_metal.cc
extensions/nanoarrow_device/src/nanoarrow/nanoarrow_device_metal_test.cc
extensions/nanoarrow_device/src/nanoarrow/nanoarrow_device_test.cc
extensions/nanoarrow_ipc/src/apps/dump_stream.c
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder.c
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder_test.cc
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_files_test.cc
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_reader.c
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_reader_test.cc
python/src/nanoarrow/_lib.pyx
r/src/array_stream.c
r/src/convert_array_stream.c
src/nanoarrow/array.c
src/nanoarrow/array_stream.c
src/nanoarrow/array_stream_test.cc
src/nanoarrow/array_test.cc
src/nanoarrow/nanoarrow.h
src/nanoarrow/nanoarrow_hpp_test.cc
src/nanoarrow/nanoarrow_testing.hpp
src/nanoarrow/nanoarrow_types.h
src/nanoarrow/schema.c
src/nanoarrow/schema_test.cc
src/nanoarrow/utils.c
src/nanoarrow/utils_test.cc

This PR adds thin wrappers around C function pointers (like is done in Arrow C++) for Arrow C Data/Stream interface structures and uses them in all tests and internal code. The motivation for this was:
- Calling `x.release(&x)` is a tiny bit verbose and involves specifying `x` twice
- Wrappers make it easier to debug (by breakpoint or via debug checks)
- Iterating through streams is very verbose if you want to catch all the error messages (in some places of the code it looks like I didn't bother, and in other places it looks like I assumed that the result of `get_last_error` was non-NULL, which is not true). The wrappers let you do `NANOARROW_RETURN_NOT_OK(ArrowArrayStreamGetNext(stream, out, error))` which better integrates into the nanoarrow error handling pattern.
The changes are:
- …

refactor: Add wrappers around callbacks to improve syntax and debuggability

---

docs/source/reference/testing.rst

Correct typo in testing.rst

---

r/R/array-stream.R
r/inst/include/nanoarrow/r.h
r/man/array_stream_set_finalizer.Rd
r/src/Makevars
r/src/array.c
r/src/array.h
r/src/array_stream.c
r/src/array_stream.h
r/src/array_view.c
r/src/as_array.c
r/src/convert.c
r/src/convert_array.c
r/src/convert_array_stream.c
r/src/infer_ptype.c
r/src/pointers.c
r/src/schema.c
r/src/schema.h
r/tests/testthat/test-array-stream.R

In developing geoarrow, an R extension that imports/exports a number of Arrow C data structures wrapped by nanoarrow S3 objects, it has become apparent that the sanitize and allocate operations are non-trivial and basically have to be copied in every package that wants to import/export nanoarrow things. @eddelbuettel has run up against some valid use-cases as well! https://github.com/eddelbuettel/linesplitter/issues/1 , https://github.com/apache/arrow-nanoarrow/issues/187
This PR makes the definition of how Arrow C Data interface objects are encoded as R external pointers available as a public header (such that downstream packages can `LinkingTo: nanoarrow` and `#include <nanoarrow/r.h>`. I think the initial target will just be allocate an owning external pointer and sanitize an input …

feat(r): Provide LinkingTo headers for extension packages

---

.github/workflows/r-check.yaml
CMakeLists.txt
r/R/buffer.R
r/src/altrep.c
r/src/array.c
r/src/array_view.c
r/src/as_array.c
r/src/buffer.c
r/src/buffer.h
r/src/convert_array_stream.c
r/src/materialize.c
r/src/materialize_chr.h
r/src/materialize_common.h
r/src/materialize_int.h
r/src/pointers.c
r/src/schema.c
r/src/util.c
r/src/util.h
r/tests/testthat/test-buffer.R
src/nanoarrow/array.c
src/nanoarrow/array_inline.h
src/nanoarrow/array_test.cc
src/nanoarrow/buffer_inline.h
src/nanoarrow/buffer_test.cc
src/nanoarrow/nanoarrow.h
src/nanoarrow/nanoarrow_hpp_test.cc
src/nanoarrow/nanoarrow_types.h
src/nanoarrow/schema.c
src/nanoarrow/schema_test.cc

As noted in https://github.com/apache/arrow-nanoarrow/issues/224, we can use a format check attribute to ensure that format strings/types match and check that `ArrowErrorCode` is always checked.
While I was in it for compiler warnings, I enabled a few more that recently caused a problem in the Arrow R package.
To minimize impact on existing usage, these are only enabled when `NANOARROW_DEBUG` is defined (as it is for all CMake debug builds and in our CI).

chore: Enable more compiler warnings

---

.github/workflows/python-wheels.yaml
dev/release/utils-prepare.sh
python/.gitattributes
python/MANIFEST.in
python/bootstrap.py
python/pyproject.toml
python/setup.py
python/src/nanoarrow/__init__.py
python/src/nanoarrow/_static_version.py
python/src/nanoarrow/_version.py
python/tests/test_capsules.py
python/tests/test_device.py
python/tests/test_nanoarrow.py
python/tests/test_version.py

This PR adds a weekly/workflow dispatch job for building and testing Python wheels. This required a few housekeeping items:
- Versioning the python package. I used the approach from ADBC, which is a modified 'miniver'. Basically, just set the version as a string using a regex replace when needed.
- The bootstrap.py logic was updated to use a proper temporary directory
- Tests were updated to skip instead of fail when pyarrow/numpy are not available (because I can never remember which platforms they will or won't install on and the default cibuildwheel grid is large).
- I hadn't tested install from sdist, so a few files were missing from the manifest.
Two outstanding issues that don't necessarily need to be solved in this PR:
- The linux arm self-hosted runner not is not picking up the …

ci(python): Add cibuildwheel setup for Python wheels

---

.github/workflows/docker-build.yaml
ci/docker/centos7.dockerfile
ci/docker/ubuntu.dockerfile

...also builds arm images in the arm runner instead of using emulation. This is needed to run verification for Python (since we'll need to build a Python extension).

chore(ci): Add Python development files to verification images and build

---

src/nanoarrow/nanoarrow_testing.hpp

As discussed in #362, we see a nag from `g++` 13.2.0 about a 'pessimizing move' from this `std::move` and the compiler itself suggests removing it.  Did so, and did not tickle a valgrind issue is casual testing.

[c++] Remove one std::move avoiding 'pessimizing move' (closes #362)

---

.github/workflows/coverage.yaml
.github/workflows/python.yaml
.github/workflows/verify.yaml
ci/scripts/coverage.sh
dev/release/verify-release-candidate.sh
python/bootstrap.py
python/pyproject.toml
python/setup.py
python/src/nanoarrow/_lib.pyx
python/src/nanoarrow/_static_version.py
python/tests/test_version.py

This PR adds Python to the coverage and verify workflows (except on centos7, where the image isn't set up for a supported version of Python yet). There were also some housekeeping issues identified by various logs that I noticed in the process (e.g., fixing the Python dev version format, ensuring that CMAKE_BIN is respected in bootstrap.py).

chore(ci): Integrate Python into more CI workflows

---

CMakeLists.txt
src/nanoarrow/array_inline.h
src/nanoarrow/array_stream.c
src/nanoarrow/nanoarrow_types.h
src/nanoarrow/utils.c

When using as a dependency and trying to use Wextra these generate warnings

Suppress unused variable warnings

---

dev/release/.gitignore
dev/release/01-prepare.sh
dev/release/02-sign.sh
dev/release/changelog.py
dev/release/test_changelog.py
dev/release/update-changelog.py

Closes #310.
Basically `cz ch` was constantly doing the wrong thing...for the last two releases I had to do quite a lot of manual editing after it was run. The Python script that replaces it:
- Can run more than once (replaces the target version's updates if commits were added)
- Groups components (e.g., so I can copy/paste the R NEWS more readily)
- Knows about when nanoarrow considers the last version "released"

chore: Replace CHANGELOG generator

---

r/tests/testthat/test-schema.R
src/nanoarrow/nanoarrow_testing_test.cc
src/nanoarrow/nanoarrow_types.h
src/nanoarrow/schema.c
src/nanoarrow/schema_test.cc

Closes #312.
`ArrowSchemaViewInit()` is called every time a schema is about to be interpreted (or an array corresponding to that schema is about to be interpreted), and so checking the flags is a must to ensure some future unsupported flag that affects the interpretation of an array will cause an error.
The `ArrowSchemaView` should arguably also keep track of `flags` (or perhaps each flag individually), but I will leave that to another PR.

feat: Check flags field of ArrowSchema on ArrowSchemaViewInit

---

r/.Rbuildignore
r/.gitignore
src/nanoarrow/buffer_inline.h
src/nanoarrow/nanoarrow.hpp
src/nanoarrow/nanoarrow_hpp_test.cc
src/nanoarrow/utils.c
src/nanoarrow/utils_test.cc

This PR makes it more predictable to work with custom allocators, including the `ArrowBufferDeallocator` that powers the R and (soon) Python "build from buffers" behaviour. It also improves testing for using custom allocators and adds a templated C++ wrapper.

fix: Ensure that the deallocator called by ArrowBufferDeallocator() is called exactly once

---

.github/workflows/python-wheels.yaml
python/.gitignore
python/MANIFEST.in
python/bootstrap.py
python/setup.py
python/src/nanoarrow/_ipc_lib.pyx
python/src/nanoarrow/_lib.pyx
python/src/nanoarrow/_repr_utils.py
python/src/nanoarrow/c_lib.py
python/src/nanoarrow/ipc.py
python/tests/test_c_buffer.py
python/tests/test_ipc.py
python/tests/test_nanoarrow.py

This PR adds bindings to nanoarrow's (high-ish level) IPC reader. There are some lower-level concepts that might be nice to expose at some point but the `ArrowArrayStream` implementation lets users realize most of the benefit.
I am envisioning that there will be a higher level `ArrayStream` class than the `CArrayStream`, so I am not sure that the current interface (create a `Stream`, then use `na.c_array_stream()`) will be the one users actually use to access this. Probably something more like `na.ArrayStream.from_stream([path or url or file])` would be appropriate. I held off on writing the Examples section until the first round of review in case there's a better way to go about this!
nanoarrow's reader is not as fast as pyarrow's using its internal filesystem (which might do memory …

feat(python): Add bindings for IPC reader

---

.github/workflows/bundle.yaml

This was failing because it didn't call `apt-get update`; however, CMake is installed anyway on the runner (so no need to install it again).

chore(ci): Fix bundler action

---

python/src/nanoarrow/_ipc_lib.pyx
python/src/nanoarrow/_lib.pyx
python/src/nanoarrow/c_lib.py
python/src/nanoarrow/iterator.py
python/tests/test_c_array.py
python/tests/test_c_array_stream.py
python/tests/test_c_buffer.py
python/tests/test_c_buffer_view.py
python/tests/test_c_schema_view.py
python/tests/test_iterator.py
python/tests/test_nanoarrow.py

This PR adds a framework for Python object creation from arrays and array streams with implementations for most arrow types. Notably, it includes implementations for nested types (struct, list, dictionary) to make sure that the framework won't have to be completely rewritten to accommodate them. A few types (decimal, datetime) aren't supported but should be reasonably easy to implement by wrapping existing iterator factories included in this PR.
None of these are exposed with `import nanoarrow as na` yet...I'm anticipating that the user-facing `nanoarrow.Array` and/or `nanoarrow.ArrayStream` to use the implementation here in methods.
A few changes were required at a lower level to make this work:
- It is now possible to use nanoarrow's `ArrowBasicArrayStream` implementation to create a …

feat(python): Add CArrayView -> Python conversion

---

.github/workflows/docker-build.yaml

This is an attempt to fix the Build Docker Images workflow (which runs once a week).
For the last few weeks we've had errors with HTTP timeouts like:
```
Error: Error response from daemon: Get "https://ghcr.io/v2/": Get "https://ghcr.io/token?account=paleolimbot&client_id=docker&offline_token=true&service=ghcr.io": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) (Client.Timeout exceeded while awaiting headers)
```
Or
```
Pushing verify (ghcr.io/apache/arrow-nanoarrow:archlinux-amd64)...
The push refers to repository [ghcr.io/apache/arrow-nanoarrow]
[12125] Failed to execute script docker-compose
Traceback (most recent call last):
File "urllib3/response.py", line 436, in _error_catcher
File "urllib3/response.py", line 518, in read …
```

chore(ci): Fix container build action

---

CMakeLists.txt
CMakePresets.json
src/nanoarrow/array_benchmark.cc
src/nanoarrow/array_view_benchmark.cc
src/nanoarrow/nanoarrow_types.h
src/nanoarrow/schema_benchmark.cc

This PR adds an initial set of benchmarks covering some realistic usage patterns. The general approach is to use doxygen comments to document the benchmarks, which will run against the released version and the previous version. I'm not sure exactly what the output format will be but I'd like the benchmarks to be written in such a way that there's a path to programatically generating a report (maybe using conbench, maybe just a Quarto document).
Work in progress!

chore: Add basic benchmark suite to C library

---

.github/workflows/build-and-test-device.yaml
.github/workflows/build-and-test-ipc.yaml
.github/workflows/build-and-test.yaml
ci/scripts/build-arrow-cpp-minimal.sh

This PR removes the use of the debian packages for Arrow C++ in favour of a minimal (cached) build. This is slightly faster than installing and removes the dependence on the artifactory for CI to pass (which is temporarily not available).
It also updates some of the actions, which were using old checkout/cache versions or installing Arrow C++ unnecessarily.
Closes #408.

fix(ci): Use cached Arrow C++ build in CI

---

README.md

The file is actually named `nanoarrow.c`

fix(docs): Correct typo in README.md

---

r/tests/testthat/test-ipc.R
r/tests/testthat/test-pkg-arrow.R

The `utils::zip()` function is not all that reliable; however, we only use it to create test data anyway. This was causing release verification to fail on alpine.
While running the tests, I also noticed that one of the IPC skips that checks for Arrow dataset does so incorrectly.

fix(r): Fix tests for platforms where arrow dataset and/or zip is not available

---

extensions/nanoarrow_device/src/nanoarrow/nanoarrow_device.c
extensions/nanoarrow_device/src/nanoarrow/nanoarrow_device_test.cc
python/src/nanoarrow/_lib.pyx
python/src/nanoarrow/_repr_utils.py
python/src/nanoarrow/array.py
python/src/nanoarrow/c_lib.py
python/src/nanoarrow/device.py
python/src/nanoarrow/nanoarrow_device_c.pxd
python/tests/test_array.py
python/tests/test_c_array.py
python/tests/test_device.py

When device support was first added, the `CArrayView` was device-aware but the `CArray` was not. This worked well until it was clear that `__arrow_c_array__` needed to error if it did not represent a CPU array (and the `CArray` had no way to check). Now, the `CArray` has a `device_type` and `device_id`. A nice side-effect of this is that we get back the `view()` method (whose removal @jorisvandenbossche had lamented!).
This also implements the device array protocol to help test https://github.com/apache/arrow/pull/40717 . This protocol isn't finalized yet and I could remove that part until it is (although it doesn't seem likely to change).
The non-cpu case is still hard to test without real-world CUDA support...this PR is just trying to get the right information in the right place as …

feat(python): Clarify interaction between the CDeviceArray, the CArrayView, and the CArray

---

dev/benchmarks/c/array_benchmark.cc
extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_flatcc_generated.h
python/tests/test_c_buffer.py
src/nanoarrow/array_test.cc
src/nanoarrow/buffer_test.cc
src/nanoarrow/integration/c_data_integration.cc
src/nanoarrow/nanoarrow.hpp
src/nanoarrow/nanoarrow_hpp_test.cc
src/nanoarrow/nanoarrow_testing.hpp
src/nanoarrow/nanoarrow_testing_test.cc
src/nanoarrow/schema_test.cc
src/nanoarrow/utils_test.cc

The latest verification run has a few outstanding errors ( https://github.com/apache/arrow-nanoarrow/actions/runs/8584808770/job/23525503382 ):
- One file was missing an `#include <array>`
- A Python test error message was hard-coded for little-endian systems
This also fixes a mountain of compiler warnings because of `-Wmisleading-indentation` on gcc that result from the flatcc generated header. These warnings made it difficult to find the Python test message error.
There were also a few other compiler warnings that I noticed when compiling the tests with Meson. Meson compiles tests with `-Wall` and I don't think CMake compiles them with anything in particular (we do compile the C libraries with many warning flags).

chore: Fix errors and compiler warnings on verification platforms

---

python/pyproject.toml
python/src/nanoarrow/iterator.py
python/tests/test_iterator.py

This PR adds support for converting Arrow date, time, timestamp, and duration arrays to Python objects. 
```python
import datetime
import zoneinfo
dt = datetime.datetime.now()
list(na.Array(pa.array([dt])).iter_py())
#> [datetime.datetime(2024, 4, 8, 16, 25, 41, 216438)]
dt_tz = datetime.datetime.now(zoneinfo.ZoneInfo("America/Halifax"))
list(na.Array(pa.array([dt_tz])).iter_py())
#> [datetime.datetime(2024, 4, 8, 16, 29, 7, 226832, tzinfo=zoneinfo.ZoneInfo(key='America/Halifax'))]
tdelta = datetime.timedelta(123, 456, 678)
list(na.Array(pa.array([tdelta])).iter_py())
#> [datetime.timedelta(days=123, seconds=456, microseconds=678)]
just_time = datetime.time(15, 27, 43, 12)
list(na.Array(pa.array([just_time])).iter_py())
#> [datetime.time(15, 27, …
```

feat(python): Add Arrow->Python datetime support

---

examples/linesplitter/CMakeLists.txt

This is a very minor 'quality of life' improvement to `linesplitter` as `cmake` nags about the minimum requirement being after (rather than before) the main project declaration, and increasing the version (which I understand you may not want to increase by as much) silences the TIMESTAMP nag.  Feel free to adjust or ignore, I just liked the quieter build.

Increase CMake minimum version, move requirement

---

python/src/nanoarrow/iterator.py
python/tests/test_iterator.py

I experimented with a few different methods here...I think this one has a good balance of speed and not messing with the global precision.
```python
import decimal
from nanoarrow.iterator import iter_py
items = [decimal.Decimal("12.3450"), None, decimal.Decimal("1234567.3456")]
array = pa.array(items, pa.decimal128(11, 4))
list(iter_py(array))
#> [Decimal('12.3450'), None, Decimal('1234567.3456')]
```
This seems to be vaguely on par with pyarrow convert:
```python
import decimal
import numpy as np
from nanoarrow.iterator import iter_py
floats = np.random.random(int(1e6))
items = [decimal.Decimal(item) for item in floats]
array = pa.array(items)
%timeit array.to_pylist()
#> 799 ms ± 6.24 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
%timeit …
```

feat(python): Support Decimal types in convert to Python

---

python/src/nanoarrow/_lib.pyx
python/src/nanoarrow/c_lib.py
python/tests/test_c_array.py
python/tests/test_c_buffer.py
python/tests/test_iterator.py

First, this PR fixes the rather uninformative error that occurs on any error while building an Array (closes #423). The error is now:
```python
na.Array([1, 2, 3])
#> ValueError
#> ...
#> An error occurred whilst converting object of type list to nanoarrow.c_array_stream or nanoarrow.c_array: 
#> schema is required for CArray import from iterable
```
Second, this PR adds support for `None` in iterables. This makes it much more convenient to create arrays with nulls (closes #424).
```python
na.Array([1, 2, None, 4], na.int32())
#> nanoarrow.Array<int32>[4]
#> 1
#> 2
#> None
#> 4 
```
Finally, this PR tweaks the implementation of packing an iterable into a buffer to avoid the very bad performance that existed previously. The optimizations added …

chore(python): Restructure buffer packing to support nulls and improve performance

---

src/nanoarrow/array.c
src/nanoarrow/array_test.cc
src/nanoarrow/integration/c_data_integration.cc
src/nanoarrow/nanoarrow_testing.hpp
src/nanoarrow/nanoarrow_testing_test.cc

These changes are the changes required such that https://github.com/apache/arrow/pull/39302 results in passing integration tests for nanoarrow. The changes are mostly related to comparison:
- We needed an option to allow metadata to be compared on a key/value basis without considering order (for Java, which seems to reorder metadata on read)
- We needed the ability to treat NULL metadata and zero-size metadata as equivalent (for Go, which always exports zero-length metadata)
- We needed an option to ignore flags for top-level batches (for C#, which exports nullable structs)
- We needed to ensure that the last few bits of the validity buffer were zeroed (for C#, although this is now fixed in C# on Arrow main)
- We needed to ensure that no buffers were NULL (For C#, which leaks the …

fix: Relax comparison strictness such that integration tests pass

---

extensions/nanoarrow_ipc/src/nanoarrow/nanoarrow_ipc_decoder.c
src/nanoarrow/schema.c
src/nanoarrow/utils.c

It is difficult, but not impossible, to get `snprintf()` to return -1, and there are a number of places where we call it on untrusted user input. This PR ensures that the return value of all `snprintf()` calls is checked.

fix: Ensure negative return values from snprintf() are not used as indexes

---

.github/workflows/python-wheels.yaml
python/bootstrap.py
python/src/nanoarrow/_lib.pyx
python/src/nanoarrow/c_lib.py
python/tests/test_c_array.py
python/tests/test_c_buffer.py
python/tests/test_iterator.py

This PR adds support for building string and binary arrays via iterable.
It also cleans up a few parts of #426 that resulted in the wheel builds failing for (at least) PyPy 3.8 and 3.9. We can circle back to the performance of building from iterables (and whether or not `pack_into()` is essential) when all the wheels are building reliably.
```python
strings = ["pizza", "yogurt", "noodles", "peanut butter sandwiches"]
na.Array(strings, na.string())
#> nanoarrow.Array<string>[4]
#> 'pizza'
#> 'yogurt'
#> 'noodles'
#> 'peanut butter sandwiches'
na.Array((s.encode() for s in strings), na.binary())
#> nanoarrow.Array<binary>[4]
#> b'pizza'
#> b'yogurt'
#> b'noodles'
#> b'peanut butter sandwiches'
```
The "build from iterable" code is now sufficiently complicated that it …

feat(python): Create string/binary arrays from iterables

---

src/nanoarrow/nanoarrow.h

A pretty harmless typo in the docs header.

fix(docs): Fix typo in documentation for `ArrowSchemaSetTypeUnion()`

---

python/tests/test_capsules.py

In pyarrow 16.0.0, per-batch casting is now implemented for array streams and tables (which invalidates an assumption made in nanoarrow's tests).

fix(python): Update tests for pyarrow 16

---

python/src/nanoarrow/_repr_utils.py
python/src/nanoarrow/array.py
python/tests/test_array.py

Addresses https://github.com/apache/arrow-nanoarrow/issues/435
Reusing the existing repr utilities, the current code gives this:
```
In [1]: import nanoarrow as na
In [2]: pa_arr = pa.array([[0, 1], [None, 3], None, [4]])
In [3]: arr = na.Array(pa_arr)
In [4]: arr.inspect()
<ArrowArray list<item: int64>>
- length: 4
- offset: 0
- null_count: 1
- buffers[2]:
- validity <bool[1 b] 11010000>
- data_offset <int32[20 b] 0 2 4 4 5>
- dictionary: NULL
- children[1]:
'item': <ArrowArray int64>
- length: 5
- offset: 0
- null_count: 1
- buffers[2]:
- validity <bool[1 b] 11011000>
- data <int64[40 b] 0 1 0 3 4>
- dictionary: NULL
- children[0]:
```

feat(python): function to inspect a single-chunk Array

---

python/src/nanoarrow/__init__.py
python/src/nanoarrow/array.py
python/tests/test_array.py

Closes https://github.com/apache/arrow-nanoarrow/issues/434

feat(python): add back nanoarrow.array(..) constructor

---

python/src/nanoarrow/array.py
python/src/nanoarrow/iterator.py
python/tests/test_array.py
python/tests/test_iterator.py

The idea with this change is to support efficient buffer access for chunked/streaming input (e.g., make a numpy array). The efficient implementation is compact but I am not sure it is easy to guess for anybody not familiar with nanoarrow internals:
```python
with c_array_stream(obj, schema) as stream:
for array in stream:
view = array.view()
```
I'm not sure that `iter_chun_data()` is the best name here, but one would use it like:
```python
array = na.Array([1, 2, 3], na.int32())
for view in array.iter_chunk_data():
print(view.offset, view.length, list(view.buffers))
#> 0 3 [nanoarrow.c_lib.CBufferView(bool[0 b] ), nanoarrow.c_lib.CBufferView(int32[12 b] 1 2 3)]
```
This would replace `iter_buffers()` which is a little dangerous to use (since one might assume the …

feat(python): Iterate over array buffers

---

python/src/nanoarrow/__init__.py
python/src/nanoarrow/array_stream.py
python/src/nanoarrow/ipc.py
python/tests/test_array_stream.py
python/tests/test_ipc.py

This class provides an interface to the ArrowArrayStream whose methods return `Schema`s and `Array`s. It also provides a more ergonomic interface to the `ipc.Stream` interface.
```python
na.ArrayStream([1, 2, 3], na.int32())
#> <nanoarrow.ArrayStream: Schema(INT32)>
na.ArrayStream([1, 2, 3], na.int32()).read_all()
#> nanoarrow.Array<int32>[3]
#> 1
#> 2
#> 3
url = "https://github.com/apache/arrow-experiments/raw/main/data/arrow-commits/arrow-commits.arrows"
na.ArrayStream.from_url(url).read_all()
#> nanoarrow.Array<struct<commit: string, time: timestamp('us', 'UTC'), ...>[15487]
#> {'commit': '49cdb0fe4e98fda19031c864a18e6156c6edbf3c', 'time': datetime.datet...
#> {'commit': '1d966e98e41ce817d1f8c5159c0b9caa4de75816', 'time': datetime.datet...
#> {'commit': …
```

feat(python): Add user-facing ArrayStream class

---

python/.gitignore
python/MANIFEST.in
python/bootstrap.py
python/setup.py

Even though the binaries were quite small, nanoarrow's wheels were about 1 MB and the installed size was about 5 MB. This is because the flatcc headers and cython generated code was rather extensive and had ended up in the built wheel. After this change the wheels are ~400kb and installed size is 1.5 MB (for me).
The main change here is to move the directory where we vendor the C files from elsewhere in the repo outside `src/` such they are not automatically included in the wheel.

chore(python): Remove C sources from wheels

---

python/src/nanoarrow/__init__.py
python/src/nanoarrow/array.py
python/src/nanoarrow/c_array.py
python/src/nanoarrow/c_array_stream.py
python/src/nanoarrow/c_schema.py
python/src/nanoarrow/schema.py
python/tests/test_array.py
python/tests/test_c_array.py
python/tests/test_c_buffer_view.py
python/tests/test_c_schema.py
python/tests/test_capsules.py
python/tests/test_ipc.py
python/tests/test_nanoarrow.py
python/tests/test_schema.py

This PR cleans up the top-level namespace such that more advanced concepts that might be confusing to new nanoarrow users are tucked away in modules (i.e., they can be used and are documented, but better alternatives are likely to be discovered first). The changes are:
- `allocate_c_array()`, `allocate_c_schema()`, and `allocate_c_array_stream()` were removed. These are useful for testing invalid input but pretty much nothing else.
- `c_array_view()` and `c_schema_view()` were removed. These are tools used by the iterators, the `Array`, and the `Schema`, but most people should use the higher level concepts for buffer access.
- A `schema()` alias for `Schema()` was added (because it is easy to accidentally type `schema()` and get a wildly inappropriate error message). This mirrors …

chore(python): Clean up top-level namespace

---

python/src/nanoarrow/_lib.pyx
python/tests/test_c_buffer_view.py

In prototyping a real-world use case, I remembered that unpacking bits is exceedingly difficult to get right if you need to support an arbitrary offset/length. The math for this is very fiddly and we spent a few rounds getting it right in the C function `ArrowBitsUnpackInt(8|32)`. This PR makes that available so that we can do things like (1) convert bool arrays to numpy and (2) convert null masks to something that somebody else can work with (e.g., a numpy mask).
This seems to be relatively performant (thanks to @WillAyd's work optimizing this!)
```python
import numpy as np
bool_np = np.random.random(int(1e6)) > 0.5
bool_na = na.Array(iter(bool_array), na.bool_())
bool_pa = pa.array(bool_np)
def to_numpy_na(x):
x_view = na.c_array(x).view()
out …
```

feat(python): Implement bitmap unpacking

---

python/src/nanoarrow/_lib.pyx
python/tests/test_c_array.py

This PR updates the logic that creates a "shallow copy" of an `ArrowArray`. Before, it simply made a shallow copy of the outer array, which works in most cases. However, the spec allows for "moving" child arrays, which means that the guarantee of a valid *outer* array does not guarantee anything about the validity of the `ArrowArray*` child pointers. It's difficult, but possible, to trigger this in Python (below); however, I think this sort of code is common for importers (because it allows the lifecycle of columns in an array to be independent).
```python
array = na.c_array_from_buffers(
na.struct({"col1": na.int32()}),
3,
[None],
children=[na.c_array([1, 2, 3], na.int32())]
)
user_array = na.Array(array)
user_array
#> nanoarrow.Array<int32>[3] …
```

fix(python): Make shallow CArray copies less shallow to accomodate moving children

---

dev/benchmarks/README.md
dev/benchmarks/python/array.py

We had renamed `bool()` to `bool_()`, which had caused the benchmarks to fail. I also documented how to run the Python benchmarks (since I'd forgotten since writing them!).

chore(dev/benchmarks): Fix Python benchmarks

---

ci/scripts/test-python-wheels.sh
python/tests/test_c_array.py

PyPy's garbage collector/object deletion is not as predictable as CPython's, so you can't be sure that when you run `gc.collect()` that all unreferenced objects will be removed, and when you `del` an object, basically nothing happens (except that future garbage collections might destroy it). I did check to make sure the deleters are actually running on pypy (using `brew install pypy3.10`) manually and added a wrapper around cibuildwheel such that one can check pypy locally when debugging one of these issues.

fix(python): Ensure reference-counting tests are skipped on PyPy

---

python/src/nanoarrow/_lib.pyx
python/src/nanoarrow/array.py
python/src/nanoarrow/c_array_stream.py
python/src/nanoarrow/iterator.py
python/tests/test_array.py
python/tests/test_c_array_stream.py
python/tests/test_c_schema.py
python/tests/test_capsules.py
python/tests/test_device.py
python/tests/test_ipc.py
python/tests/test_nanoarrow.py

This PR adds a public route to construct chunked arrays (and makes the other constructors safer to account for the fact that they are now user-facing). I use this quite a lot interactively to test that things work in the chunked case, and for nanoarrow to be useful in a "I can help you export things" kind of way, it needs to be able to do this (because string arrays with more than 2 GB of text or binary are not uncommon).
The main safety consideration here is ensuring that all chunks have a schema of the same type, so I had to add a function to check for that (and ensure it was being checked).
```python
import numpy as np
na.Array.from_chunks([[1, 2, 3], [4, 5, 6]], na.int32())
na.Array.from_chunks((np.random.random(int(1e3)) for _ in range(int(1e3))))
```

feat(python): Add `Array.from_chunks()` constructor

---

python/src/nanoarrow/_lib.pyx
python/src/nanoarrow/_repr_utils.py
python/src/nanoarrow/array.py
python/src/nanoarrow/array_stream.py
python/src/nanoarrow/c_array_stream.py
python/src/nanoarrow/ipc.py
python/src/nanoarrow/iterator.py
python/src/nanoarrow/schema.py
python/tests/test_c_schema.py
python/tests/test_nanoarrow.py
python/tests/test_schema.py

This PR unifies how types are printed, which was different among the `Array`, `Scalar`, `ArrayStream`, and `Schema`. These now all use the same function such that type information is communicated in a consistent way for all user-facing classes.
The general approach is to print all possible information on the first line. Most types have descriptions like `int32`, so this is a good fit and there's no need for multiple lines. This makes a list of schemas (e.g., `schema.fields`) have a nice repr, too. The Schema repr additionally prints out metadata if present (this is skipped by the other classes).
Some examples:
```python
na.int32()
#> <Schema> int32
na.fixed_size_binary(123)
#> <Schema> fixed_size_binary(123)
na.int32(nullable=False)
#> <Schema> non-nullable int32 …
```

feat(python): Unify printing of type information across classes

---

python/src/nanoarrow/_lib.pyx
python/tests/test_c_buffer_view.py

This is small change to ensure that `np.array(some_buffer.unpack_bits())` "just works" without nanoarrow having to know about numpy dtypes. Basically we just need to ensure that we can create/export a buffer with a `"?"` format string.
```python
import numpy as np
bool_array = na.Array([True, True, True, False, False, True], na.bool_())
np.array(bool_array.buffer(1).unpack_bits(0, len(bool_array)))
#> array([ True,  True,  True, False, False,  True])
```

feat(python): Ensure that buffer produced by `CBufferView.unpack_bits()` has a boolean type

---

python/src/nanoarrow/_lib.pyx
python/tests/test_c_buffer_view.py

This is the non-bitmap equivalent of #450, useful for the same purpose (concatenating one big data buffer from chunks).

feat(python): Add copy_into() to CBufferView

---

python/src/nanoarrow/_lib.pyx
python/src/nanoarrow/array.py
python/src/nanoarrow/array_stream.py
python/src/nanoarrow/iterator.py
python/src/nanoarrow/visitor.py
python/tests/test_array.py
python/tests/test_array_stream.py
python/tests/test_visitor.py

Assembling columns from chunked things is rather difficult to do and is a valid thing that somebody might want to assemble from Arrow data. This PR adds a "visitor" pattern that can be extended to build "column"s, which are currently just `list()`s. Before trimming down this PR to a managable set of changes, I also implemented the visitor that concatenates data buffers for single data buffer types ( https://gist.github.com/paleolimbot/17263e38b5d97c770e44d33b11181eaf ), which will be needed for `to_columns()` to be used in any kind of serious way.
To support the "visitor" pattern, I moved some of the `PyIterator`-specific pieces into the `PyIterator` so that the visitor can re-use the relevant pieces of `ArrayViewBaseIterator`. This pattern also solves one of the problems I had when …

feat(python): Add visitor pattern + builders for column sequences

---

python/src/nanoarrow/iterator.py
python/tests/test_iterator.py

Closes #465.
```python
arr = na.array(pa.array([None]))
arr.schema
#> <Schema> na
arr
#> nanoarrow.Array<na>[1]
#> None
```

fix(python): Add iterator for null/na type

---

src/nanoarrow/nanoarrow.hpp
src/nanoarrow/nanoarrow_hpp_test.cc

Apparently gcc4.8 takes issue with the use of braces in some places and does not provide `is_trivially_copyable()` or `std::size()` 🤷 
Closes #462 .
Tested via
```
export NANOARROW_PLATFORM=centos7
export NANOARROW_ARCH=arm64  # because I'm on MacOS M1
docker compose run --rm verify
```

fix: Ensure nanoarrow.hpp compiles on gcc 4.8

---

README.md

docs: Update top-level documentation

---

dev/release/verify-release-candidate.sh
r/.Rbuildignore

It seems that running R CMD INSTALL is not sufficient on Windows to vendor the proper files. It may have worked by accident in the past because the vendored files already existed in my local checkout. I don't think there are many people verifying on Windows; however I think removing `configure.win` (since it seems not to run anyway) and configure on build is a better option.

chore(dev/release): Do nanoarrow vendoring using R_BIN instead of R CMD INSTALL on Windows

---

python/src/nanoarrow/__init__.py
python/src/nanoarrow/_lib.pyx
python/src/nanoarrow/array.py
python/src/nanoarrow/array_stream.py
python/src/nanoarrow/iterator.py
python/src/nanoarrow/visitor.py
python/tests/test_array.py
python/tests/test_array_stream.py
python/tests/test_c_buffer.py
python/tests/test_nanoarrow.py
python/tests/test_visitor.py

This PR implements building columns buffer-wise for the types where this makes sense. It also implements a few other changes:
- `item_size` was renamed to `itemsize` to match the memoryview property name
- The visitor methods are now the `ArrayViewVisitable` mixin such that they are available in both the `Array` and `ArrayView` without duplicating documentation.
Functionally this means that the `Array` and `ArrayStream` now have `to_column()` and `to_column_list()` methods that do something that more closely matches what somebody would expect.
A quick demo:
```python
batch = pa.record_batch({"col1": [1, 2, 3], "col2": ["a", "b", "c"]})
batch_with_nulls = pa.record_batch({"col1": [1, None, 3], "col2": ["a", "b", None]}) …
```

feat(python): Add column-wise buffer builder

---

python/src/nanoarrow/_lib.pyi
python/src/nanoarrow/_lib.pyx
python/src/nanoarrow/visitor.py
python/tests/test_c_buffer.py

At least one test is failing on pypy because of an unreleased buffer. This was due to the line:
```python
memoryview(builder)[out_start : out_start + length] = b"\x01" * length
```
...which relied on the deletion of `memoryview(builder)` to release the `builder` buffer. One solution is:
```python
with memoryview(builder) as mv:
mv[out_start : out_start + length] = b"\x01" * length
```
However, we also have `ArrowBufferAppendFill()` in the C library, so instead, this PR wires that up and uses it (which should be faster, anyway).

fix(python): Fix use of memoryview to write fill to the buffer builder

---

python/tests/test_c_buffer.py

Apparently the context manager for the memoryview does not promptly release its source buffer in PyPy 3.8. This PR skips the one assertion where this matters on just that platform.

fix(python): Skip test relying on memoryview context manager on PyPy 3.8

---

python/tests/test_c_buffer.py

...apparently my local PyPy test was not sufficient to ensure that all the tests pass on PyPy. This seems to be specific to the `memoryview()` (not C extensions that properly release the buffer).

chore(python): Skip buffer write lock test on PyPy

---

CMakeLists.txt
extensions/nanoarrow_device/CMakeLists.txt

This is part of a solution to #407 in that it enables `cmake . -DNANOARROW_IPC=ON`; however, I don't think it completely solves it since I am not sure that the full suite of bundle/install/fetchcontent will work here yet.
The motivation for this is to make it easier to move pieces of the extensions into the main nanoarrow library that make sense (e.g., the definitions for the device structs), and eventually eliminate the extensions folder. I am planning in the next month or so to clean up the device extension and after that to work on the write component of the IPC extension. In combination with the testing utilities that were recently added, I think it makes the most sense for these to live at the top level and be developed together.

chore: Enable extensions to be built from the main CMake project

---

dev/release/README.md

A few post-release items were undocumented. They are also good candidates for future automation (but at least now they are documented!)

chore(dev/release): Document missing pieces of release process

---

r/src/Makevars

Closes #493.
We could be fancier and check for the presence of aligned_alloc() or guard it in a define based on the C standard; however, I don't think we use it at all right now and even when write support is added I don't think it will matter for how we use flatbuffers in the IPC format.

fix(r): Avoid flatcc aligned_alloc() call when compiling R package

---

src/nanoarrow/meson.build

May not necessarily fix https://github.com/apache/arrow-nanoarrow/issues/495 but reasonably defers trying to solve
Basically the suggestion of the great @eli-schwartz

fix: Force static library build on Windows when building with Meson

---

src/nanoarrow/array_inline.h
src/nanoarrow/array_test.cc

Hi this PR adds float16 support for `ArrowArrayViewGet{Double,Int,UInt}Unsafe()`. Related issue: #500

feat: Add float16 support for `ArrowArrayViewGet{Double,Int,UInt}Unsafe()`

---

dev/release/README.md

We're now in WrapDB, so we need to remember to do that! Also, some of the pre-release tasks weren't properly enumerated, and the links in the announcement could be improved (e.g., it should be linking to the official documentation and the release blog post).

chore(dev/release): Update documentation for post-release tasks

---

.gitignore
README.md
ci/scripts/build-with-meson.sh
dev/benchmarks/c/array_benchmark.cc
dev/benchmarks/c/schema_benchmark.cc
dev/release/rat_exclude_files.txt
meson.build
meson.options
src/nanoarrow/meson.build
subprojects/google-benchmark.wrap
subprojects/gtest.wrap
subprojects/nlohmann_json.wrap

Two main changes here:
1. Changed options like `NANOARROW_BUILD_TESTS` to just `tests`
2. Included wrap files into repository, rather than requiring user to install
Point 1 was inspired by looking at other projects in the wrap database. Note that if multiple projects were being compiled at once and there was some ambiguity between options, you can namespace providing them on the command line by using the form `<project>:<option>`, ex: `meson configure -Darrow:tests=true`

refactor!: More idiomatic meson usage

---

extensions/nanoarrow_device/CMakeLists.txt
extensions/nanoarrow_device/src/nanoarrow/nanoarrow_device.c
extensions/nanoarrow_device/src/nanoarrow/nanoarrow_device.h
extensions/nanoarrow_device/src/nanoarrow/nanoarrow_device_cuda.c
extensions/nanoarrow_device/src/nanoarrow/nanoarrow_device_cuda_test.cc
extensions/nanoarrow_device/src/nanoarrow/nanoarrow_device_metal.cc
extensions/nanoarrow_device/src/nanoarrow/nanoarrow_device_metal_test.cc
extensions/nanoarrow_device/src/nanoarrow/nanoarrow_device_test.cc

Closes #246.
This PR doesn't change much about the existing implementation (and I think there are some things that need to be changed!), it just eliminates the dependency on the runtime library. The driver API is a better fit here anyway since we're doing very low-level things!
This isn't tested in CI yet (working on that here: https://github.com/apache/arrow-nanoarrow/pull/490 ).

refactor(extensions/nanoarrow_device): Migrate CUDA device implementation to use the driver API

---

python/src/nanoarrow/_lib.pyx
python/src/nanoarrow/nanoarrow_device_c.pxd

#488 broke the Python package build (which I'd forgotten uses the device extension).

chore(python): Add `sync_event` argument to Python .pxd header

---

src/nanoarrow/array.c
src/nanoarrow/array_inline.h
src/nanoarrow/array_test.cc
src/nanoarrow/nanoarrow.h
src/nanoarrow/nanoarrow_types.h
src/nanoarrow/schema.c
src/nanoarrow/schema_test.cc
src/nanoarrow/utils.c

Hi this PR tries to add support for run-end encoded array based on the arrow spec here, https://arrow.apache.org/docs/format/Columnar.html#run-end-encoded-layout.

feat: Add support for run-end encoded array

---

src/nanoarrow/array.c
src/nanoarrow/array_test.cc
src/nanoarrow/schema_test.cc

Tests for https://github.com/apache/arrow-nanoarrow/pull/507 and https://github.com/apache/arrow-nanoarrow/pull/501 and/or https://github.com/apache/arrow-nanoarrow/pull/503 either used C++17 or features from Arrow C++ > 12. Our test suite still supports these (although perhaps parts of this support should be dropped soon).
On Windows, formatting with `%lu` was doing some unexpected formatting. We could do a better job formatting 64-bit integers in error messages (e.g., using `PRId64` and the requisite defines to ensure it works on mingw); however, we probably won't ever be able to support properly formatting an unsigned 64-bit integer on every platform we support. I changed the error message (and its test) slightly to reflect that.

chore(ci): Ensure tests pass for Arrow C++ <12 and on C++11

---

src/nanoarrow/array_test.cc

A follow-up to #514 for a case I missed. Again, we can do slightly better with printing large numbers in error messages (particularly on Windows), but for now the message will at least signal the gist of what happened.

chore: Slightly more lenient test for error message on Windows

---

dev/benchmarks/CMakeLists.txt
dev/benchmarks/CMakePresets.json

After #511 there is a slightly different way to build the nanoarrow with IPC support (required by benchmarks).

chore(dev/benchmarks): Add 0.5.0 release to benchmark run + enable build with against refacotred CMake

---

src/nanoarrow/array.c

This PR should fix the issue where `run_ends_view->length` is not checked if equals to 0 before attempting to access `run_ends_view`'s values. Many thanks to @WillAyd.

fix: check `run_ends_view->length` before accessing its values

---

.github/workflows/r-check.yaml

We (vaguely) follow the [tidyverse R version support policy](https://www.tidyverse.org/blog/2019/04/r-version-support/) and support the current release plus the last four releases. Relatedly, our test dependencies no longer support R 3.6 and this CI job is failing.

chore(r): Bump minimum supported R version to 4.0

---

src/nanoarrow/array_test.cc
src/nanoarrow/utils_test.cc

Some minor changes to correct usage that resulted in compiler warnings when opening this up and doing a naive build in VSCode on Windows.

chore: Fix compiler warnings on Windows

---

src/apps/dump_stream.c
src/nanoarrow/array.c
src/nanoarrow/nanoarrow_device.c
src/nanoarrow/nanoarrow_device_cuda.c
src/nanoarrow/nanoarrow_ipc_decoder.c
src/nanoarrow/nanoarrow_ipc_reader.c
src/nanoarrow/schema.c

Very pedantic change to the great work done in https://github.com/apache/arrow-nanoarrow/pull/507 just to prevent any issues on LLP64 systems

refactor: Use inttypes.h macros instead of casts to print fixed-width integers

---

ci/scripts/build-with-meson.sh
src/nanoarrow/meson.build
subprojects/flatcc.wrap

Follow up to https://github.com/apache/arrow-nanoarrow/pull/483

refactor: Remove CMake requirement from Meson IPC config

---

src/nanoarrow/array.c
src/nanoarrow/array_test.cc
src/nanoarrow/buffer_test.cc
src/nanoarrow/nanoarrow_testing.hpp

See https://github.com/apache/arrow-nanoarrow/pull/518#issuecomment-2161063096 . The overflow wasn't the one I'd suspected and it wasn't related to that PR (that PR/the one before it just added a test covering a case that didn't exist in our previous tests).
I also fixed some compiler warnings exposed by the meson build on linux/arm64 (where character is unsigned).

fix: Check for offset + length > int64_max before using the value to calculate buffer sizes

---

.github/workflows/build-and-test-device.yaml
src/nanoarrow/nanoarrow_device.c
src/nanoarrow/nanoarrow_device_metal.cc
src/nanoarrow/nanoarrow_device_metal.h
src/nanoarrow/nanoarrow_device_metal_test.cc

This PR fixes the Metal build (which was broken after a previous change), adds it to CI (thanks to the new GitHub M1 runners!) and fixes a failure I see locally (but not on CI) whereby the Metal runtime on some (newer? different?) MacOS environments can wrap arbitrary bytes as an `MTL::Buffer()`.
If true, this is awesome! But it does mean that in some cases we can "move" CPU arrays to the GPU without a copy and in some cases we have to copy into page-aligned memory (and that this can only be tested at runtime).

fix: Ensure ArrowDeviceArray implementation for AppleMetal passes tests on newer MacOS

---

src/nanoarrow/nanoarrow_device_cuda.c
src/nanoarrow/nanoarrow_device_cuda_test.cc

According to the CUDA docs for [cuMemAlloc](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MEM.html#group__CUDA__MEM_1gb82d2a09844a58dd9e744dc31e8aa467):
> If bytesize is 0, [cuMemAlloc()](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__MEM.html#group__CUDA__MEM_1gb82d2a09844a58dd9e744dc31e8aa467) returns [CUDA_ERROR_INVALID_VALUE](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__TYPES.html#group__CUDA__TYPES_1ggc6c391505e117393cc2558fff6bfc2e990696c86fcee1f536a1ec7d25867feeb).
We end up calling `cuMemAlloc()` with `0` bytesize when allocating device buffers with no null mask. Thus, the following change was causing `nanoarrow_device_cuda_test` to fail:
```diff
@@ -207,7 +207,8 @@ TEST_P(StringTypeParameterizedTestFixture, ArrowDeviceCudaArrayViewString) { …
```

fix(Python): Ensure we don't call cuMemAlloc with 0 bytesize

---

.github/workflows/examples.yaml
CMakeLists.txt
ci/scripts/bundle.py
meson.build
src/meson.build
src/nanoarrow/meson.build
src/nanoarrow/nanoarrow_types.h

Quick follow up to https://github.com/apache/arrow-nanoarrow/pull/508 - the array.c includes stopped working without this
```
FAILED: libnanoarrow.so.p/src_nanoarrow_array.c.o 
ccache cc -Ilibnanoarrow.so.p -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c99 -O0 -g -fPIC -MD -MQ libnanoarrow.so.p/src_nanoarrow_array.c.o -MF libnanoarrow.so.p/src_nanoarrow_array.c.o.d -o libnanoarrow.so.p/src_nanoarrow_array.c.o -c ../src/nanoarrow/array.c
../src/nanoarrow/array.c:23:10: fatal error: nanoarrow/nanoarrow.h: No such file or directory
23 | #include "nanoarrow/nanoarrow.h"
|          ^~~~~~~~~~~~~~~~~~~~~~~
```

fix: Fix Meson include directories

---

src/nanoarrow/array_test.cc
src/nanoarrow/buffer_test.cc
src/nanoarrow/nanoarrow.hpp
src/nanoarrow/nanoarrow_device_cuda_test.cc
src/nanoarrow/nanoarrow_device_metal_test.cc
src/nanoarrow/nanoarrow_device_test.cc
src/nanoarrow/nanoarrow_hpp_test.cc
src/nanoarrow/nanoarrow_testing_test.cc
src/nanoarrow/schema_test.cc
src/nanoarrow/utils_test.cc

In https://github.com/apache/arrow-nanoarrow/pull/404, the `_v` literal was added, making it much more compact to define an `ArrowStringView` and compare its equality to something else.
This PR refactors tests that used `EXPECT/ASSERT_EQ()` to be more compact, and replaces `ArrowCharView()` with the string literal.
From reading https://en.cppreference.com/w/cpp/string/basic_string_view/operator%22%22sv and https://json.nlohmann.me/api/macros/json_use_global_udls/#notes it seems like constraining the user-defined literal to a namespace is the "modern" way to do this...I am not sure that `"_sv"` is the best choice (maybe too close to `"sv"`?), but it did seem more descriptive than `"_v` for those reading the tests without knowing that these literals are defined.

refactor: Use ArrowStringView C++ literal in tests

---

.github/workflows/python-wheels.yaml

We had been building wheels on macOS-11, but that runner will be disabled at the end of the week. The updated documentation for cibuildwheel suggests using macOS-13 and macOS-14 (for x86 and arm, respectively), and the updated cibuildwheel version supports building for pyodide!

chore(ci): Fix wheel building workflow and add pyodide wheels

---

python/setup.py
python/src/nanoarrow/_device.pxd
python/src/nanoarrow/_device.pyx
python/src/nanoarrow/_lib.pyx
python/src/nanoarrow/array.py
python/src/nanoarrow/device.py

Similar to previous PRs, this PR moves the device class definition into its own module. Both arrays and buffers are device-aware, so splitting the device definition is a prerequisite.

refactor(python): Split device functionality into its own module

---

.github/workflows/docker-build.yaml

It looks like at least one mirror/package we need is no longer installable, so we can no longer rebuild the centos7 image weekly with the rest of the images. (We can still pull the existing image for testing, though).

fix(ci): Stop building unbuildable image based on centos7

---

.github/workflows/verify.yaml
CMakeLists.txt
valgrind.supp

There are a few problems in the verification workflow:
- On Windows, we weren't exporting any symbols in the C data integration test (when building with CMake)
- The R package testthat doesn't seem to support centos7, which we would need to test the R package there
- The R package jsonlite seems to leak memory. One fix is https://github.com/jeroen/jsonlite/pull/442 , but in the meantime we can ignore the leak since it doesn't come from us.

fix(ci): Fix verification workflow

---

thirdparty/googletest/CMakeLists.txt
thirdparty/nlohmann_json/CMakeLists.txt

closes https://github.com/apache/arrow-nanoarrow/issues/309

Fix: CMake deprecation warnings from subprojects

---

python/src/nanoarrow/_lib.pyx
r/src/materialize_unspecified.h
src/nanoarrow/common/array_test.cc
src/nanoarrow/common/inline_array.h
src/nanoarrow/nanoarrow.h
src/nanoarrow/nanoarrow_testing.hpp
thirdparty/zlib/CMakeLists.txt

Adds `ArrowArrayViewComputeNullCount()` and tests. Extracted from https://github.com/apache/arrow-nanoarrow/pull/555

add ArrowArrayViewComputeNullCount

---

CMakeLists.txt
ci/scripts/bundle.py
src/nanoarrow/ipc/decoder.c
src/nanoarrow/ipc/decoder_test.cc
src/nanoarrow/ipc/encoder.c
src/nanoarrow/ipc/encoder_test.cc
src/nanoarrow/nanoarrow_ipc.h
src/nanoarrow/nanoarrow_ipc.hpp

Add `ArrowIpcEncoder`, init/reset, and tests. Extracted from https://github.com/apache/arrow-nanoarrow/pull/555#pullrequestreview-2186295630

feat: Add IPC writer scaffolding

---

src/nanoarrow/ipc/decoder_test.cc
src/nanoarrow/ipc/encoder.c
src/nanoarrow/ipc/encoder_test.cc
src/nanoarrow/nanoarrow_ipc.h

- added ArrowIpcEncoderEncodeSchema
- added a parameter to ArrowIpcEncoderFinalizeBuffer which controls whether encapsulated/padded message buffers will be produced instead of raw
- tests reuse the decoder tests, replacing arrow C++'s encoder with ArrowIpcEncoder
Extracted from https://github.com/apache/arrow-nanoarrow/pull/555#pullrequestreview-2186295630

feat: Add IPC schema encoding

---

CMakeLists.txt
ci/scripts/bundle.py
meson.build
src/nanoarrow/ipc/encoder.c
src/nanoarrow/ipc/ipc_hpp_test.cc
src/nanoarrow/ipc/writer.c
src/nanoarrow/ipc/writer_test.cc
src/nanoarrow/nanoarrow_ipc.h
src/nanoarrow/nanoarrow_ipc.hpp

This is a prerequisite for adding nanoarrow to the IPC integration tests (since we'll need a full stream writer into which we'll push batches, which will need an output stream into which it'll push bytes).

feat: add ArrowIpcOutputStream

---

.github/workflows/r-check.yaml

First noticed at https://github.com/apache/arrow-nanoarrow/pull/555#discussion_r1702201173 , the R check action is failing because an update to r-lib actions resulted in some quarto actions being invoked, and these have not yet been whitelisted for use in Apache repositories. It also may be that we don't need the quarto actions (we probably don't) but some brief experimentation to attempt circumventing the use of the quarto action did not result in a successful workflow. Hence, a pin to unblock PR checks until either the v2 branch is updated or it is clear how to avoid the failure.

fix(ci): Pin r-lib actions as a workaround for latest action updates

---

meson.build
meson.options

After https://github.com/apache/arrow-nanoarrow/pull/561 , the nanoarrow_testing library is no longer header-only and requires linking!

fix: Fix Meson build for separated nanoarrow_testing target

---

CMakeLists.txt
src/nanoarrow/device/cuda.c
src/nanoarrow/device/metal.cc
src/nanoarrow/device/metal_impl.cc
src/nanoarrow/device/metal_impl.h
src/nanoarrow/ipc/decoder.c
src/nanoarrow/ipc/encoder.c
src/nanoarrow/testing/testing.cc

In previous PRs we consolidated the extensions into the main CMakeLists.txt; however, there were some things happening for certain targets (like installing them or setting NANOARROW_DEBUG) but not others.
Noticed in https://github.com/apache/arrow-nanoarrow/pull/555#discussion_r1702103767 where there was a DCHECK referencing a variable that didn't exist that made it through CI 😬

refactor: Consolidate per-target actions in CMakeLists.txt

---

.github/workflows/verify.yaml
CMakeLists.txt
src/nanoarrow/common/array_test.cc
src/nanoarrow/ipc/decoder_test.cc
src/nanoarrow/ipc/encoder.c
src/nanoarrow/ipc/writer_test.cc

Noted in the weekly verification run: https://github.com/apache/arrow-nanoarrow/actions/runs/10232042714/job/28308701770
I think there were a three issues:
- The bundling setup used a feature of the command execution not available in stock `cmake3` on centos7
- Some C++17 (or unsupported gcc4.8 C++11) in some of the newer IPC additions
- IPC tests were failing on big endian ( https://github.com/apache/arrow-nanoarrow/actions/runs/10232042714/job/28308702337#step:4:2640 )
Reproducible via:
```shell
export NANOARROW_PLATFORM=centos7
docker compose run -e TEST_PYTHON=0 -e TEST_R=0 --rm verify
```
```shell
export NANOARROW_PLATFORM=alpine
export NANOARROW_ARCH=s390x
docker compose run -e TEST_DEFAULT=0 -e TEST_C=1 --rm verify
```

fix(ci): Fix build and test of nanoarrow on centos7 and s390x

---

.github/workflows/r-check.yaml
CMakeLists.txt
src/nanoarrow/ipc/decoder.c
src/nanoarrow/ipc/decoder_test.cc
src/nanoarrow/ipc/encoder.c
src/nanoarrow/ipc/encoder_test.cc
src/nanoarrow/nanoarrow_ipc.h

- added `ArrowIpcEncoderEncodeRecordBatch()`
- added `ArrowIpcEncoderBuildContiguousBodyBuffer()` to provide a default buffer encoder implementation which simply concatenates a batch's buffers into one contiguous (properly aligned and padded) body buffer
- testing uses the decoder tests, replacing arrow C++'s encoder with the new nanoarrow encoder

feat: add ipc RecordBatch encoding

---

src/nanoarrow/common/inline_buffer.h
src/nanoarrow/common/inline_types.h
src/nanoarrow/ipc/encoder.c
src/nanoarrow/ipc/files_test.cc
src/nanoarrow/ipc/writer.c
src/nanoarrow/nanoarrow_ipc.h
src/nanoarrow/nanoarrow_ipc.hpp
valgrind.supp

- adds ArrowIpcArrayStreamWriter along with Init() and Reset() methods
- embeds an Encoder and an OutputStream
- adds WriteSchema() and WriteArrayView() methods which encode then write a schema or array
- adds WriteArrayStream() method which serializes an entire ArrowArrayStream, finishing with an explicit EOS
- non-blocking IO is not currently supported

feat: Add IPC stream writing

---

src/nanoarrow/common/array.c
src/nanoarrow/common/array_test.cc
src/nanoarrow/common/inline_types.h
src/nanoarrow/nanoarrow.h

This PR is one possible component to address #577. While in some cases we want a more relaxed comparison that allows (for example) arrays with the same content to be considered equal even if they have different content in null slots, in some cases we really do want an exact match. This PR adds `ArrowArrayViewCompare()` in such a way that the same signature could be used to apply the equality check at a more relaxed validation level when this is implemented in a future PR, but only implements the "identical" level since this is the easiest/most pressing (applies to IPC validation).
The messages given by the implementation give the location of the difference but not what the difference actually was. Knowing where the error was is usually sufficient for a higher level runtime (e.g., R, …

feat: Add `ArrowArrayViewCompare()` to check for array equality

---

src/nanoarrow/ipc/encoder.c
src/nanoarrow/ipc/files_test.cc
src/nanoarrow/ipc/writer.c

- As noted https://github.com/apache/arrow-nanoarrow/pull/571#discussion_r1712730976 RecordBatch Messages were not being written during IPC streaming. This has been corrected
- Testing uses one more round trip case where we have arrow C++ read from a stream written by nanoarrow.
- During testing it also became apparent that encapsulated messages were not always stored with the correct size; metadata_size should include padding (but not the continuation or size itself) https://arrow.apache.org/docs/format/Columnar.html#encapsulated-message-format

fix: IPC streams did not include RecordBatch headers

---

CMakeLists.txt
src/nanoarrow/common/array.c
src/nanoarrow/common/inline_types.h
src/nanoarrow/integration/ipc_integration.cc
src/nanoarrow/ipc/encoder.c
src/nanoarrow/ipc/encoder_test.cc
src/nanoarrow/ipc/json_integration.cc
src/nanoarrow/ipc/reader.c
src/nanoarrow/ipc/writer.c
src/nanoarrow/ipc/writer_test.cc
src/nanoarrow/nanoarrow_ipc.h
src/nanoarrow/nanoarrow_ipc.hpp

- Adds a new executable for use with the archery integration tests
- When reading files, it ignores the Footer entirely
- A few private workarounds are added, most notably the stream writer tracks Blocks in order to populate the Footer
- Tested against patched archery https://github.com/apache/arrow/compare/main...bkietz:arrow:nanoarrow-integration-tests
- issue to add nanoarrow to the tests https://github.com/apache/arrow/issues/43680

feat: Add IPC integration test executable

---

src/nanoarrow/integration/ipc_integration.cc

Minor patch to the integration executable; Java produces IPC files with potentially reordered metadata: https://github.com/apache/arrow/actions/runs/10410485727/job/28832431571?pr=43715#step:9:9093

fix: don't require metadata order in nanoarrow_ipc_integration

---

src/nanoarrow/nanoarrow.hpp

Encountered in an ADBC build:
https://github.com/apache/arrow-adbc/actions/runs/10424783996/job/28874300812#step:10:830
```
D:\a\arrow-adbc\arrow-adbc\adbc\c\vendor\nanoarrow\nanoarrow.hpp(829,21): warning C4355: 'this': used in base member initializer list [D:\a\arrow-adbc\arrow-adbc\adbc\build\driver\framework\adbc_driver_framework.vcxproj]
```

fix: Silence warning when compiling nanoarrow.hpp on at least one version of MSVC

---

.github/workflows/docker-build.yaml
CMakeLists.txt
src/nanoarrow/ipc/encoder_test.cc

We have several errors in the weekly jobs:
- Some runners no longer have `docker-compose`, so we need to switch to `docker compose`.
- There was a missing `#include <stdio.h>` in `array.c`

fix(ci): Fix verify, meson-build, and docker-build weekly runs

---

src/nanoarrow/integration/ipc_integration.cc
src/nanoarrow/ipc/encoder.c

An absent Schema.custom_metadata was causing flatcc to produce invalid flatbuffers on s390x. For now, just populate that field with an empty vector

fix: Ensure that schema metadata is always present even if empty

---

src/nanoarrow/integration/ipc_integration.cc
src/nanoarrow/ipc/decoder.c
src/nanoarrow/ipc/decoder_test.cc
src/nanoarrow/ipc/encoder.c
src/nanoarrow/nanoarrow_ipc.h

- Adds ArrowIpcDecoderPeekFooter(), ArrowIpcDecoderVerifyFooter(), and ArrowIpcDecoderDecodeFooter()
- Uses these to read IPC files in the integration test executable

feat: add Footer decoding

---

src/nanoarrow/integration/ipc_integration.cc
src/nanoarrow/ipc/decoder.c
src/nanoarrow/ipc/encoder.c

During encoding, `Field.nullable` was not coerced to 0 or 1 (I was expecting `flatcc` to do that). However the Go reader recognizes anything other than `Field.nullable == 1` as a non-nullable field
https://github.com/google/flatbuffers/issues/8389
some typos and better error messages are included

fix: ensure 1 is written for boolean True

---

meson.build
src/nanoarrow/common/buffer_test.cc
src/nanoarrow/common/inline_buffer.h
src/nanoarrow/ipc/decoder_test.cc

The meson build is broken without this dependency. Also fixed up a few warnings around unused variables and the use of uninitialized struct members

test: Fix meson build and clean up some warnings

---

.github/workflows/python-wheels.yaml

This fixes the python-wheels action (failing on main).

chore(ci): Use setup-python action on self-hosted arm64 runner

---

CMakeLists.txt

Some local update on my local machine resulted in nanoarrow not compiling because clang gave a warning for the C11 extensions in the flatcc generated code. I believe this was because the C standard had already been set to C99 at the beginning of the file, whereas the check to update it to C11 only happened after this had already been set.

chore: More reliable definition of C standard in CMakeLists

---

.github/workflows/docker-build.yaml
.github/workflows/integration.yaml
.github/workflows/python-wheels.yaml
.github/workflows/verify.yaml
ci/docker/alpine.dockerfile
docker-compose.yml
src/nanoarrow/ipc/reader_test.cc
src/nanoarrow/ipc/writer_test.cc

This PR:
- Updates the integration test workflow to not cache a weekly build, which was failing with "no space left on device". It also runs more tests than are strictly necessary at the commit level (and takes slightly longer without the cached weekly build), so this PR makes it part of a weekly run instead.
- Updates the alpine dockerfile to avoid a `desc` dependency, since this fails to install on s390x
- Update two tests to account for a function that returns the value of `errno` (that might not be the same everywhere)
It also updates the weekly jobs for consistency:
- Updates the weekly jobs to always run on the `maint-**` branches
- Update all of them to cancel previous runs of the same workflow (because many of them have long-running jobs)
It doesn't fix IPC writing on big endian …

chore(ci): Fix failing weekly jobs

---

dev/benchmarks/python/ipc.py
python/src/nanoarrow/_ipc_lib.pyx
python/src/nanoarrow/array.py
python/src/nanoarrow/array_stream.py
python/src/nanoarrow/ipc.py
python/src/nanoarrow/schema.py
python/tests/test_array.py
python/tests/test_array_stream.py
python/tests/test_ipc.py
python/tests/test_schema.py

This PR implements bindings to the IPC writer in the nanoarrow C library. This adds:
- An `ipc.StreamWriter()` class roughly mirroring pyarrow's `ipc.Stream()`
- `Schema.serialize()` and `Array.serialize()` to match pyarrow's `serialize()` methods.
```python
import io
import nanoarrow as na 
from nanoarrow.ipc import StreamWriter, InputStream
out = io.BytesIO()
writer = StreamWriter.from_writable(out)
writer.write_stream(InputStream.example())
na.Array(InputStream.from_readable(out.getvalue()))
#> nanoarrow.Array<non-nullable struct<some_col: int32>>[3]
#> {'some_col': 1}
#> {'some_col': 2}
#> {'some_col': 3}
```

feat(python): Implement bindings to IPC writer

---

.github/workflows/build-and-test-device.yaml

The self-hosted CUDA runner was updated and contains a different set of packages than the old one. A few updates required!

chore(ci): Update library installs for self-hosted CUDA runner

---

docker-compose.yml

Thanks to https://github.com/apache/arrow/issues/44062 , we can run fewer jobs in our integration test matrix (and benefit from better GitHub actions grouping!).

chore(ci): Use ARCHERY_INTEGRATION_TEST_TARGET_LANGUAGES to reduce integration test matrix

---

src/nanoarrow/ipc/decoder.c
src/nanoarrow/ipc/decoder_test.cc

This PR fixes the verification run failure for big endian, which is currently failing on the `NanoarrowIpcNanoarrowFooterRoundtrip` tests. Checked with:
```bash
export NANOARROW_ARCH=s390x
docker compose run --rm verify
```

fix: Ensure footer test passes on big endian

---

.github/workflows/verify.yaml
src/nanoarrow/ipc/writer.c
valgrind.supp

Also fixes a leak that was identified by the R bindings to the IPC writer.
Closes #579 (apparently the flatcc update was sufficient to eliminate the suppression!)

chore: Update valgrind suppressions after internal flatcc update

---

docs/source/roadmap.md

The roadmap contained some (very) oudated ideas regarding ideas for future scope. This PR updates them with more recent text based on the existing list of issues and implementation work that has happened over the past few months.

chore(docs): Ensure roadmap is up-to-date

---

.github/workflows/integration.yaml
ci/docker/integration.dockerfile
docker-compose.yml
src/nanoarrow/common/array.c
src/nanoarrow/common/array_test.cc

This PR updates validation of offset buffers in string/binary, large string/binary, list, and large list types such that portions of the buffers not strictly required by the slice referenced by `offset` and `length` are not accessed/validated. This came up in the IPC integration tests because C# exports full buffers rather than the portions of buffers strictly required.
This highlights how our test suite would benefit from helpers to reduce repetition (although I'd prefer to handle that at a later time if possible).

fix: Improve validation of offset buffers for sliced arrays

---

src/nanoarrow/common/array.c
src/nanoarrow/common/array_test.cc
src/nanoarrow/common/inline_array.h

Similar to #626 but for union type_id arrays. This should fix the two remaining failures in the integration tests between the IPC implementations in the Arrow repository and the nanoarrow IPC implementation https://github.com/apache/arrow/pull/43715.

fix: Only validate relevant type_ids for array view slice

---

.github/workflows/python-wheels.yaml
python/setup.py

This PR updates the Python packaging to build a single nanoarrow library that is shared amongst the various extension modules and updates the version of cibuildwheel such that we can release Python 3.13 wheels in our upcoming release. I'm not sure where the mechanism used to build a "shared" library is documented, nor am I sure that it is truly a "shared" library (may be static); however, it seems conceptually better than the existing system of compiling the source files more than once for each module that needed them.

chore(python): Update Python packaging

---

src/nanoarrow/ipc/decoder.c

For metadata versions before V5, ignore the extra validity bitmap. If the bitmap is non-empty, we raise an error (which is the same bail used in arrow-C++ and -java).

fix: ignore empty (but present) union validity bitmaps from before 1.0

---

python/src/nanoarrow/_repr_utils.py
python/src/nanoarrow/schema.py
python/tests/test_schema.py

Fix https://github.com/apache/arrow-nanoarrow/issues/466
```
>>> import nanoarrow as na
>>> url = "https://github.com/apache/arrow-experiments/raw/main/data/arrow-commits/arrow-commits.arrows"
>>> schema = na.ArrayStream.from_url(url).schema
>>> schema
<Schema> non-nullable struct<commit: string, time: timestamp('us', 'UTC'), files: int32, merge: bool, message: string>
```

fix: python schema repr does not truncate output

---

r/R/convert-array.R
r/R/extension.R
r/man/convert_array.Rd
r/tests/testthat/test-extension.R

Closes #631.
``` r
array <- as_nanoarrow_array(data.frame(x = 1:5, y = letters[1:5]))
array$children$z <- nanoarrow_extension_array(letters[1:5], "some_extension")
tibble::as_tibble(array)
#> Warning in warn_unregistered_extension_type(x): z: Converting unknown extension
#> some_extension{string} as storage type
#> Warning in warn_unregistered_extension_type(storage): z: Converting unknown
#> extension some_extension{string} as storage type
#> # A tibble: 5 × 3
#>       x y     z    
#>   <int> <chr> <chr>
#> 1     1 a     a    
#> 2     2 b     b    
#> 3     3 c     c    
#> 4     4 d     d    
#> 5     5 e     e
options(nanoarrow.warn_unregistered_extension = FALSE)
tibble::as_tibble(array)
#> # A tibble: 5 × 3
#>       x y     z    
#>   <int> <chr> <chr>
#> 1     1 …
```

feat(r): Allow opt-out of warning for unregistered extension types

---

valgrind.supp

This suppression was annotated "Can be removed when https://github.com/jeroen/jsonlite/pull/442 is released". This PR can serve as a placeholder for that until it is released

chore: Remove valgrind suppression for R bindings after updated jsonlite release

---

src/nanoarrow/common/array.c
src/nanoarrow/common/array_test.cc
src/nanoarrow/common/inline_array.h

closes https://github.com/apache/arrow-nanoarrow/issues/634

fix; Properly ingest Binary View types without variadic buffers

---

python/src/nanoarrow/_array.pyx
python/tests/test_c_array.py
r/src/array.c
r/src/buffer.c
r/tests/testthat/_snaps/array.md
src/nanoarrow/common/array.c
src/nanoarrow/common/array_test.cc
src/nanoarrow/common/inline_array.h
src/nanoarrow/common/inline_types.h
src/nanoarrow/common/schema_test.cc
src/nanoarrow/common/utils.c
src/nanoarrow/nanoarrow.h
src/nanoarrow/testing/testing.cc

This PR abstracts accessors for the buffer_view, buffer type, buffer data type, and element bit width for the `ArrowArrayView`. Before adding string/binary view support, this was done by directly accessing the `layout` and `buffer_view` members; however, this required special-casing + some duplicated code in the string view in the R/Python bindings.
This PR also removes the dependence on the `ArrowArrayView::array` member, since this member is optional (i.e., the data backing an `ArrowArrayView` need not be related to an actual `ArrowArray`).

feat: Add ArrowArrayView accessors to inspect buffer properties

---

r/tests/testthat/test-ipc.R
src/nanoarrow/common/array_test.cc
src/nanoarrow/common/schema_test.cc
src/nanoarrow/ipc/decoder_test.cc

A few tests were failing on the centos7 run, which these days mostly checks for accidental C++17 or R >= 4.0 usage or Arrow > 9.0.0 usage in the tests.
Closes #640.
Checked with:
```bash
export NANOARROW_PLATFORM=centos7 
docker compose run --rm verify       
```
and
```bash
export NANOARROW_PLATFORM=alpine
export NANOARROW_ARCH=s390x
docker compose run --rm verify       
```

chore(ci): Fix tests for centos7 and s390x

---

.github/workflows/build-and-test-device.yaml

The self-hosted "cuda" runner is currently not picking up any jobs, causing CI to hang at "yellow" for several days for each run until the job times out. Until this is resolved, we need to disable that job (https://github.com/apache/arrow-nanoarrow/issues/646).

chore(ci): Temporarily disable CUDA integration jobs that are not being picked up

---

src/nanoarrow/common/inline_array.h

Identified as a compiler error in MSVC when testing against ADBC.

fix: Remove unreachable code

---

docker-compose.yml
src/nanoarrow/ipc/decoder.c
src/nanoarrow/ipc/decoder_test.cc
src/nanoarrow/ipc/reader.c
src/nanoarrow/nanoarrow_ipc.h

Closes #641.
Unfortunately we just have to skip checking Rust compatibility due to https://github.com/apache/arrow-rs/issues/5052 (e.g., https://github.com/apache/arrow-rs/pull/6449 ).
This PR also ensures compatibility with big endian Arrow files and Arrow files from before the continuation token. Support for those had already been added in the decoder but hadn't made it to the stream reader yet.
Local check:
```bash
export gold_dir=../arrow-testing/data/arrow-ipc-stream/integration 
export ARROW_NANOARROW_PATH=$(pwd)/build 
pip install -e "../arrow/dev/archery/[all]"
archery integration --with-nanoarrow=true --run-ipc \
--gold-dirs=$gold_dir/0.14.1 \
--gold-dirs=$gold_dir/0.17.1 \
--gold-dirs=$gold_dir/1.0.0-bigendian \
--gold-dirs=$gold_dir/1.0.0-littleendian \ …
```

chore(ci): Ensure integration workflow passes

---

.github/workflows/build-and-test-device.yaml

chore(ci): Reenable CUDA runner on device workflow

---

r/src/as_array.c
r/src/infer_ptype.c
r/src/materialize_dbl.h
r/tests/testthat/test-as-array.R
r/tests/testthat/test-convert-array.R

I'd forgotten to do this after the addition of float16 <-> double conversion in the C library!
``` r
array <- as_nanoarrow_array(1.23 + 1:5, schema = na_half_float())
convert_array(array)
#> [1] 2.228516 3.228516 4.226562 5.226562 6.226562
```
<sup>Created on 2024-10-07 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

feat(r): Add float16 support for R bindings

---

dev/release/README.md
r/bootstrap.R

This PR updates dev/release/README.md with the new version numbers, including a few changes that were required based on updated versions of the referenced images. I also had to be more flexible about the `python` used by the R package to do the bundling since on Windows `python3` launches an interactive Window and fails (while `python` is the thing that gets installed more typically by the Python installer).
I removed centos7 from the directions since that image no longer exists! (We still test against it in CI using an old previously built image).

chore(dev/release): Update verification instructions for forthcoming release

---

dev/release/02-sign.sh

We don't upload R package to GitHub Releases by GH-541. So we don't need to sign it.
Closes #654.

chore(dev/release): Update sign targets

---

src/nanoarrow/nanoarrow.hpp

Clang warns about this.  Apparently GCC 4.9 may warn about the fixed syntax, though!
Spotted in the ADBC CI:
```
/adbc/c/vendor/nanoarrow/nanoarrow.hpp:94:35: error: identifier '_asv' preceded by whitespace in a literal operator declaration is deprecated [-Werror,-Wdeprecated-literal-operator]
94 | inline ArrowStringView operator"" _asv(const char* data, std::size_t size_bytes) {
|                        ~~~~~~~~~~~^~~~
|                        operator""_asv
```

fix: remove deprecated operator"" syntax usage

---

src/nanoarrow/integration/ipc_integration.cc
src/nanoarrow/nanoarrow.hpp
src/nanoarrow/nanoarrow_device.hpp
src/nanoarrow/nanoarrow_testing.hpp
src/nanoarrow/testing/testing.cc

There were still a number of implementation details left in nanoarrow_testing.hpp. As part of the effort to improve the testing utilities and remove the Arrow C++ requirement, a few things might need to get added here and this seemed like a good place to start.

chore: Improve tidiness of nanoarrow_testing.hpp

---

.github/workflows/build-and-test.yaml
meson.build
src/nanoarrow/ipc/decoder_test.cc

closes https://github.com/apache/arrow-nanoarrow/issues/672

clean: Assorted Meson and clang-tidy fixes

---

.github/workflows/benchmarks.yaml
dev/benchmarks/CMakeLists.txt
dev/benchmarks/CMakePresets.json

PyArrow no longer lists numpy as a dependency, but we used it to generate random data for the benchmarks. We also needed to add a preset for 0.6.0.

chore: Update benchmarks workflow for new nanoarrow/pyarrow

---

ci/scripts/build-docs.sh
python/src/nanoarrow/array.py
src/apidoc/Doxyfile

Because we had moved some headers outside of src/nanoarrow into src/nanoarrow/common, they weren't getting included in the documentation!
We can't quite add  `-W` to the sphinx build command (error for warnings) because pandoc doesn't generate .rst files that are warning free (and we use pandoc to avoid having to write tutorials in restructured text).
Closes #676.

docs: Ensure all headers are parsed by Doxygen

---

.github/workflows/r-check.yaml
.github/workflows/verify.yaml

Closes #357, succeeds #358, and removes a workaround that existed before a specific action had been whitelisted by infra (it now is!).

chore(ci): Verify on 32-bit Windows

---

.pre-commit-config.yaml

Before this PR, running `pre-commit run --all-files` was not sufficient to result in passing CI (particularly on MacOS, where the brew installed clang-format is considerably newer than the CI-installed clang-format). This PR just makes the version that had been enforced in CI part of the configuration.

chore(ci): Ensure clang-format version is consistent in pre-commit

---

r/src/as_array.c
r/tests/testthat/test-as-array.R

Before we had been punting to the arrow R package for this which wasn't necessary! This was exposed by a test that had been added for matrix support that wasn't skipped if arrow wasn't installed.
``` r
as_nanoarrow_array(1:10, schema = na_double())
#> <nanoarrow_array double[10]>
#>  $ length    : int 10
#>  $ null_count: int 0
#>  $ offset    : int 0
#>  $ buffers   :List of 2
#>   ..$ :<nanoarrow_buffer validity<bool>[null] ``
#>   ..$ :<nanoarrow_buffer data<double>[10][80 b]> `1 2 3 4 5 6 7 8 9 10`
#>  $ dictionary: NULL
#>  $ children  : list()
```
<sup>Created on 2024-12-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

feat(r): Support native creation of more numeric Arrow arrays from integer vectors

---

src/nanoarrow/common/utils_test.cc
src/nanoarrow/hpp/view.hpp
src/nanoarrow/hpp/view_test.cc

closes https://github.com/apache/arrow-nanoarrow/issues/701

fix(cpp): Fix offset handling in ViewArrayAs Range Helpers

---

CMakeLists.txt
ci/docker/integration.dockerfile

This PR updates the CMake such that it works in conda after a `conda install zstd` (which doesn't provide `libzstd_static`, but does provide `libzstd`). This is needed to unskip the integration tests for zstd because the integration image uses conda ( https://github.com/apache/arrow/pull/45205 ).
Previous commits tested https://github.com/apache/arrow/pull/45205 by specifically pulling that branch instead of apache/arrow. When zstd is installed...the tests pass!

chore: Fall back on shared libzstd if libzstd_static is not available

---

.github/workflows/docker-build.yaml
.github/workflows/python-wheels.yaml

The linux arm64 runners are now GA for open source repos: https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/

chore(ci): Use Github linux arm64 runners instead of the self-hosted ones

---

src/nanoarrow/hpp/view.hpp
src/nanoarrow/hpp/view_test.cc

Closes https://github.com/apache/arrow-nanoarrow/issues/633

Implement ViewBinaryViewArrayAsBytes

---

README.md

The download link in the README is wrong and the version is outdated.

fix(docs): fix download link in the README

---

src/nanoarrow/common/schema_test.cc

This fixes a small oversight with how macros are being used to test the schema initialization of LARGE_LIST schema types

test: Test LargeList SchemaInit without Arrow

---

CMakeLists.txt

Ensures the proper target directories also on windows (`dll`s to `bin`, `lib`s to `lib`)

Fix install dirs

---

r/tests/testthat/test-array.R
r/tests/testthat/test-as-array.R
r/tests/testthat/test-buffer.R
r/tests/testthat/test-convert-array-stream.R
r/tests/testthat/test-convert-array.R
r/tests/testthat/test-extension-vctrs.R
r/tests/testthat/test-infer-ptype.R

This completes the existing set of `skip_if_not_installed()` directives

Add skips for Suggests packages

---

ci/docker/integration.dockerfile

Apply https://github.com/apache/arrow/pull/45790 / https://github.com/apache/arrow-rs/pull/7292 to fix the failing integration test job.
```
------
> [integration 5/5] RUN ARCHERY_INTEGRATION_WITH_NANOARROW="0"     conda run --no-capture-output     /arrow-integration/ci/scripts/integration_arrow_build.sh     /arrow-integration     /build:
4.312   Downloaded cfg-if v1.0.0
4.314   Downloaded async-stream v0.3.6
4.317   Downloaded anstyle v1.0.10
4.319   Downloaded adler2 v2.0.0
4.321   Downloaded http-body v1.0.1
4.374 error: package `half v2.5.0` cannot be built because it requires rustc 1.81 or newer, while the currently active rustc version is 1.77.2
4.374 Either upgrade to rustc 1.81 or newer, or use
4.374 cargo update half@2.5.0 --precise ver
4.374 where `ver` is the latest version of …
```

fix: Remove rust version pin for integration test job

---

meson.build
src/nanoarrow/nanoarrow.h
src/nanoarrow/nanoarrow_ipc.h

This is a follow up to #719 enabling hidden symbol visibility in the Meson configuration

feat: Use hidden symbol linkage in Meson configuration

---

dev/benchmarks/CMakeLists.txt

After #719, `target_link_libraries(... nanoarrow)` must be `target_link_libraries(... nanoarrow::nanoarrow)` and I'd forgotten to update the benchmarks build.

chore(dev/benchmarks): Update benchmarks build for latest CMake changes

---

.github/workflows/verify.yaml
src/nanoarrow/common/inline_types.h
src/nanoarrow/common/utils.c
src/nanoarrow/common/utils_test.cc
src/nanoarrow/ipc/decoder_test.cc
src/nanoarrow/ipc/files_test.cc

This PR fixes Decimal32 and Decimal64 handling on big endian. The previous code used a cast on the least significant word to convert between 64-bit words and the 32 bit value; however, this is only correct on big endian. This was exposed by #720, which in turn exposed that the get/set digits behaviour was not tested for Decimal 32/64. This code was updated to use a `memcpy()` instead of a cast for the 32-bit case. The s390x workflow had been failing because of a segfaulting compiler for a while and so I'd missed that the decimal 32/64 change had broken it 😬 .
There is also one change to get the Windows verification job passing that I noticed when running the verify.yaml workflow to test big endian.
This can be checked locally with:
```shell
export NANOARROW_ARCH=s390x  
docker compose run …
```

fix: ArrowDecimalSetDigits() on s390x + test fixes for big endian

---

src/nanoarrow/common/inline_array.h
src/nanoarrow/common/schema.c
src/nanoarrow/ipc/decoder.c

This patch extends int32 operands to 64 bits in arithmetic expressions where the result is assigned to int64 members, or compared with them.
Closes #735

fix: Fix potential integer overflows

---

README.md
ci/scripts/build-with-meson.sh
meson.build
meson.options
python/meson.build

The feature option is pretty similar to the previous boolean setting, but allows three states of enabled, disabled, and auto.
auto by default is disabled, but you can set `-Dauto_features=enabled` to have that toggle to enabled. By doing so, you can let users either start with nothing and opt-in to everything, or opt-in by default and then opt-out of the components they do not want

feat: Use feature options instead of boolean in Meson

---

.asf.yaml

Mailing list thread voting to enable them: https://lists.apache.org/thread/551ll326to6wflf2hp87vg01w1pq60ll
The ADBC PR I used as a template for this change: https://github.com/apache/arrow-adbc/pull/2649
I also synced a few other fields from ADBC's .asf.yaml that seemed relevant (protected branches, issues_status mailing list).

chore: Enable discussions in .asf.yaml

---

thirdparty/flatcc/include/flatcc/portable/pstdalign.h

Closes #740.
I check with `usethis::edit_r_makevars()`:
```
CC=clang -std=c2x
CFLAGS=-Wkeyword-macro
```
The error doesn't reproduce on `r-hub/containers/clang20`, possibly because it's not using `-std=c23` or didn't build clang with the option to use that as the default C standard.

chore(r): Fix -Wkeyword-macro for flatcc header when compiled with C23

---

r/src/altrep.c
r/src/altrep.h

From the CRAN check page:
```
File ‘nanoarrow/libs/nanoarrow.so’:
Found non-API call to R: ‘DATAPTR’
Compiled code should not call non-API entry points in R.
See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual,
and section ‘Moving into C API compliance’ for issues with the use of
non-API entry points.
```
When fixing this I also saw that we have conditional ALTREP usage. ALTREP has been available since R 3.5.0, which is two versions before what our CI matrix checks. I removed the conditional bits that were no longer needed (i.e., we now always assume that `R_ext/altrep.h` is available).

chore(r): Remove conditional ALTREP usage and remove call to DATAPTR

---

meson.build

This is a minor usability enhancement to use Meson's `disabler()` object rather than repeating a lot of if statements to enable/disable tests

clean: Use Meson disabler objects instead of conditions

---

.github/workflows/build-and-test.yaml
src/nanoarrow/hpp/view.hpp

I'm not sure that anything was actually wrong here, but writing it differently helped valgrind understand what's going on. I also added a pin for meson since the latest version results in failing CI when running valgrind (and opened #753 to track removing the pin).
Closes #749.

fix: Fix valgrind error suggesting use of an uninitialized value

---

.github/workflows/python-wheels.yaml

These actions are failing now since these runner are no longer available!

fix(ci): Update actions using ubuntu-20.04

---

src/nanoarrow/ipc/decoder.c

This in theory shouldn't happen because the outer code checks for a zero size specification from the IPC message header; however, we can at least make sure it is correct. (I didn't add a test because this is a static internal function).
Closes #734.

chore: fix dead code on clone of zero size shared buffer

---

src/nanoarrow/ipc/decoder.c
src/nanoarrow/ipc/decoder_test.cc

fix: Enure ArrowIpcSetDecompressor() marks input decompressor as released

---

src/nanoarrow/common/inline_buffer.h
src/nanoarrow/ipc/reader_test.cc
src/nanoarrow/ipc/writer_test.cc

I tried to add a test that would trigger the sanitizer error based on https://github.com/vyasr/nanoarrow_clang_tidy_error ; however, I think clang-tidy is too smart when it's all integrated in the same project and I don't see the error appear.
Closes #662.

chore: Help clang-tidy avoid errors when calling AppendBitmapInt8

---

ci/docker/integration.dockerfile

We need to checkout Go/Java/JS explicitly because they moved to their own repository recently.
Closes #758.

chore: enable integration tests with Go/Java/JS

---

.github/workflows/build-and-test-device.yaml
CMakeLists.txt

This is currently failing with:
```
Error when evaluating 'runs-on' for job 'test-c-device'. .github/workflows/build-and-test-device.yaml (Line: 40, Col: 14): Unexpected value ''
```
...because we'd been relying on the "empty string means ubuntu-latest" that was removed from GitHub actions at some point. There are a few updates here as well to fix the device build since that job hadn't been running for some time.

fix(ci): Fix runner specification for c-device

---

.github/workflows/python-wheels.yaml

This PR updates the python-wheels job to not use windows-2019 (which is going away soon), and adds arm64 Windows wheels (maybe).

chore(ci): Update python-wheels CI job

---

src/nanoarrow/nanoarrow_testing.hpp
src/nanoarrow/testing/testing.cc

We missed one issue in the last PR for this to work out of the box. I imagine people put std::string in headers all the time and there's another workaround here (or maybe people just ignore this warning all the time)...perhaps a better long-term solution would be to just expose a C interface here.

fix: Linking to nanoarrow-testing-shared on Windows

---

.github/workflows/python-wheels.yaml

The last time we tried this Cython wasn't ready for it but now it is!
This updates cibuildwheel to just before 3.0.0, which was released an hour ago. 3.0 includes some updates to the default manylinux and at least for this release I think we maybe can keep the old defaults (and update to 3.0 shortly after to get Python 3.14 support).
Also (possibly) fixes the gemfury nightly upload since the previous CLI is apparently deprecated.

chore(python): Add free-threaded Python wheel and update gemfury CLI client

---

ci/scripts/build-with-meson.sh
meson.build

Right now if a user wants to user the `-Dauto_features=enabled` option, some of the more obscure features have to be disabled in the majority of cases.
Rather than failing the build, I think its better to warn for some of the lesser used or available features (cuda, metal, arrow)

fix: Make auto_features more user friendly in Meson

---

.github/workflows/build-and-test.yaml
ci/scripts/build-with-meson.sh
meson.build

I have a suspicion this is why the wrapdb Windows build is failing. When developing locally, I think Meson will propogate this setting to subprojects, but when nanoarrow is itself a subproject, I don't believe this propogates to any other subprojects, and I _think_ that's why we are getting mixed build types in the Windows CI

ci: Remove Meson default_option to set buildtype of release

---

meson.build
python/src/nanoarrow/meson.build

This is a minor update per the suggestion in https://github.com/mesonbuild/wrapdb/issues/2208#issuecomment-2989884271

chore: Use better debug detection in Meson

---

CMakeLists.txt

The vcpkg checks for a dry run of the current state of the main branch ( https://github.com/microsoft/vcpkg/pull/46029 ) fail because (1) `-Werror` is always set in debug mode and there's at least one platform where we get some extra warnings and (2) we install shared libraries when static linkage was requested. This PR adds options so we can turn those off in the vcpkg config.

chore: Add options to CMake configuration for vcpkg build

---

dev/release/README.md
dev/release/verify-release-candidate.sh

Just working through these instructions to make sure everything still works!
- Remove Arrow C++ directions since it is no longer necessary for verification (Updates from https://github.com/apache/arrow-nanoarrow/pull/695/ that I'd forgotten to merge)
- Update version numbers for easier command copy/pasting
- Tweaks to dependencies required on various platforms

chore(dev/release): Update release instructions for 0.7.0

---

src/nanoarrow/common/array_test.cc
src/nanoarrow/common/inline_array.h

fix: Ensure the array view can be used to inspect map offsets

---

.github/workflows/python-wheels.yaml

https://github.blog/changelog/2025-09-19-github-actions-macos-13-runner-image-is-closing-down/
replacing with `macos-15-intel` based on
https://docs.github.com/en/actions/reference/runners/github-hosted-runners#standard-github-hosted-runners-for-public-repositories

macos-13 is deprecated
